// Curated input. Stable IDs preserve learner progress across future model edits.
// r(sourceId, firstSlide, lastSlide) always uses 1-based presentation order.
const r = (sourceId, from, to = from) => ({ sourceId, from, to });
const t = (
  id,
  eraId,
  title,
  period,
  summary,
  checkpoints,
  sources,
  related = [],
  status = "starter",
) => ({
  id,
  eraId,
  title,
  period,
  summary,
  checkpoints,
  sources,
  related,
  status,
});

export const eras = [
  {
    id: "ancient",
    title: "Ancient India",
    period: "Prehistory–c. 750 CE",
    color: "#b77930",
    question: "How did settlements become cities, states and empires?",
  },
  {
    id: "regional",
    title: "Regional kingdoms",
    period: "c. 750–1200 CE",
    color: "#ab674d",
    question: "How did regional powers shape politics, trade and culture?",
  },
  {
    id: "sultanate",
    title: "Sultanates & the Deccan",
    period: "1206–c. 1600 CE",
    color: "#7b69a4",
    question: "How were new states built, governed and contested?",
  },
  {
    id: "mughal",
    title: "Mughal India",
    period: "1526–1707 & successors",
    color: "#ad5473",
    question:
      "How did an empire connect land, military service and cultural patronage?",
  },
  {
    id: "colonial",
    title: "Company & Crown",
    period: "1498–1885",
    color: "#408d87",
    question:
      "How did traders become rulers, and how did Indian society respond?",
  },
  {
    id: "freedom",
    title: "Freedom struggle",
    period: "1885–1947",
    color: "#658343",
    question:
      "How did nationalism develop into a mass struggle for independence?",
  },
  {
    id: "republic",
    title: "Independent India",
    period: "1947 onward",
    color: "#547dac",
    question:
      "How was independence translated into a united, democratic country?",
  },
  {
    id: "world",
    title: "World history connections",
    period: "Modern world · PYQ gaps",
    color: "#85705c",
    question: "Which global processes appear in your mains questions?",
  },
];

export const topics = [
  t(
    "prehistory",
    "ancient",
    "From stone tools to farming",
    "Prehistory",
    "Track changes in tools, food production and settlement. Stone-age dates vary by region; learn the sequence before memorising a single date range.",
    [
      "Palaeolithic: hunting and gathering; Mesolithic: microliths.",
      "Neolithic: farming, domestication and polished stone tools.",
      "Chalcolithic cultures used copper alongside stone; compare settlement and pottery evidence.",
    ],
    [r("ancient", 1, 9)],
    ["harappa"],
  ),
  t(
    "harappa",
    "ancient",
    "Harappan cities & material culture",
    "Mature phase: c. 2600–1900 BCE",
    "Reconstruct urban life from archaeological evidence: sites, drainage, crafts, exchange and burial. Separate observations from interpretations of religion and government.",
    [
      "Build a site–river–find table for Harappa, Mohenjodaro, Kalibangan, Dholavira and Lothal.",
      "Connect standardised weights, seals and craft production to exchange.",
      "The script remains undeciphered; claims about beliefs and political authority need caution.",
    ],
    [r("ancient", 10, 39)],
    ["prehistory", "vedic-early", "gupta"],
  ),
  t(
    "vedic-early",
    "ancient",
    "Early Vedic society",
    "c. 1500–1000 BCE",
    "Use the Rig Veda to study pastoral life, kinship and tribal assemblies. Compare institutions with the later Vedic period.",
    [
      "Cattle had economic and social significance.",
      "Rajan, sabha and samiti belong in your polity comparison.",
      "Learn the roles of Indra, Agni and sacrificial practice.",
    ],
    [r("ancient", 40, 49)],
    ["vedic-later"],
  ),
  t(
    "vedic-later",
    "ancient",
    "Later Vedic transformation",
    "c. 1000–600 BCE",
    "Follow the movement toward settled agriculture, larger territories, ritual authority and sharper social distinctions.",
    [
      "Compare pastoral and agricultural economies.",
      "Trace changes in kingship, assemblies and varna.",
      "Distinguish royal rituals: rajasuya, ashvamedha and vajapeya.",
    ],
    [r("ancient", 50, 56)],
    ["vedic-early", "mahajanapadas"],
  ),
  t(
    "vedic-texts",
    "ancient",
    "Vedas, philosophy & literature",
    "Vedic and later textual traditions",
    "Organise texts by function rather than as an undifferentiated list of books.",
    [
      "Rig: hymns; Sama: chants; Yajur: sacrificial formulae; Atharva: spells and related traditions.",
      "Brahmanas explain rituals; Aranyakas and Upanishads develop reflection and philosophy.",
      "Distinguish shruti from smriti and identify the limits of texts as historical evidence.",
    ],
    [r("ancient", 57, 67)],
    ["vedic-later", "buddhism", "jainism"],
  ),
  t(
    "mahajanapadas",
    "ancient",
    "Mahajanapadas & the rise of Magadha",
    "c. 6th–4th centuries BCE",
    "Explain why territorial states and towns grew, and why Magadha became a major power.",
    [
      "Link agricultural surplus, iron, trade and urban growth.",
      "Compare Haryanka, Shishunaga and Nanda rulers.",
      "Track the shift from Rajagriha toward Pataliputra.",
    ],
    [r("ancient", 68, 75)],
    ["mauryas", "buddhism"],
  ),
  t(
    "buddhism",
    "ancient",
    "Buddhism: ideas, institutions & spread",
    "From the 6th century BCE",
    "Connect the Buddha’s teachings with the sangha, patronage and the growth of different traditions.",
    [
      "Explain the Four Noble Truths and the Eightfold Path.",
      "Distinguish Buddha, dhamma and sangha from the Jain three jewels.",
      "Make a council–patron–text chart; treat contested ancient dates as approximate.",
    ],
    [r("ancient", 76, 87)],
    ["jainism", "mauryas", "kushanas"],
  ),
  t(
    "jainism",
    "ancient",
    "Jainism & its traditions",
    "Early historic India",
    "Study Mahavira in the tradition of the tirthankaras and compare Jain and Buddhist paths to liberation.",
    [
      "Mahavira is traditionally the 24th tirthankara; Parshvanatha the 23rd.",
      "Right faith, right knowledge and right conduct form the three jewels.",
      "Understand ahimsa, the five vows, and Digambara and Shvetambara traditions.",
    ],
    [r("ancient", 88, 90)],
    ["buddhism"],
  ),
  t(
    "invasions-ancient",
    "ancient",
    "Persian & Macedonian contacts",
    "6th–4th centuries BCE",
    "Place northwestern India within wider political and cultural networks.",
    [
      "Distinguish Persian control from Alexander’s campaign.",
      "Locate the Hydaspes battle in 326 BCE and the encounter with Porus.",
      "Connect the aftermath of these campaigns with Mauryan expansion.",
    ],
    [r("ancient", 91, 92)],
    ["mauryas"],
  ),
  t(
    "mauryas",
    "ancient",
    "Mauryan empire & Ashoka",
    "c. 322–185 BCE",
    "Connect imperial expansion, administration and the use of inscriptions to Ashoka’s policy of dhamma.",
    [
      "Sequence Chandragupta, Bindusara and Ashoka.",
      "Use inscriptions as evidence; distinguish rock and pillar edicts.",
      "Explain the significance of Kalinga and avoid equating dhamma with a single sect’s doctrine.",
    ],
    [r("ancient", 93, 101)],
    ["mahajanapadas", "buddhism", "post-mauryas"],
  ),
  t(
    "post-mauryas",
    "ancient",
    "Shungas, Kanvas & Satavahanas",
    "After c. 185 BCE",
    "Study regional state formation after the Mauryas through coins, inscriptions and patronage.",
    [
      "Identify Pushyamitra Shunga and the Kanva succession.",
      "Connect Satavahanas to the Deccan and long-distance trade.",
      "Compare Brahmanical and Buddhist patronage without assuming they were mutually exclusive.",
    ],
    [r("ancient", 102, 109)],
    ["kushanas", "sangam"],
  ),
  t(
    "kushanas",
    "ancient",
    "Indo-Greeks, Shakas & Kushanas",
    "c. 2nd century BCE–3rd century CE",
    "Use coins, trade routes and religious art to follow connections across northwestern India and Central Asia.",
    [
      "Sequence Indo-Greek, Shaka, Parthian and Kushana powers broadly.",
      "Connect Kanishka with Buddhist patronage and Kushana power.",
      "Compare Gandhara and Mathura art traditions.",
    ],
    [r("ancient", 110, 117)],
    ["buddhism", "gupta"],
  ),
  t(
    "sangam",
    "ancient",
    "Sangam age & early Tamil society",
    "Early centuries BCE/CE",
    "Read early Tamil literature alongside archaeological evidence for trade, society and the Chera, Chola and Pandya polities.",
    [
      "Distinguish the three crowned kingdoms.",
      "Match Tolkappiyam and Tirukkural with their traditions.",
      "Connect ports, inland production and overseas exchange.",
    ],
    [r("ancient", 118, 121)],
    ["cholas"],
  ),
  t(
    "gupta",
    "ancient",
    "Guptas: empire, knowledge & culture",
    "c. 4th–6th centuries CE",
    "Study political expansion and cultural production, while testing the limits of the label “Golden Age”.",
    [
      "Use Harisena’s Allahabad pillar inscription for Samudragupta.",
      "Distinguish Chandragupta I from Chandragupta II and the Mauryan Chandragupta.",
      "Organise literature, science, art and social inequalities for a balanced mains answer.",
    ],
    [r("ancient", 122, 132)],
    ["harsha", "harappa"],
  ),
  t(
    "harsha",
    "ancient",
    "Harsha & the post-Gupta landscape",
    "c. 6th–7th centuries CE",
    "Follow the emergence of regional kingdoms and compare literary accounts with travellers’ reports.",
    [
      "Connect Harsha with the Pushyabhuti dynasty and Kannauj.",
      "Remember Xuanzang’s visit and Banabhatta’s literary account.",
      "Pulakeshin II checked Harsha’s southern expansion.",
    ],
    [r("ancient", 133, 135)],
    ["tripartite"],
  ),
  t(
    "tripartite",
    "regional",
    "Pratiharas, Palas & Rashtrakutas",
    "c. 8th–10th centuries CE",
    "Use Kannauj as the centre of a three-way political story, then compare each dynasty’s regional base and cultural patronage.",
    [
      "Pratiharas: northern and western India; Palas: Bengal and Bihar; Rashtrakutas: Deccan.",
      "Connect the Palas with Nalanda and Vikramashila.",
      "Associate Krishna I with the Kailasa temple at Ellora; verify conflicting ruler dates in the source.",
    ],
    [r("sultanate", 1, 29)],
    ["harsha", "cholas", "turkish-conquests"],
  ),
  t(
    "cholas",
    "regional",
    "Cholas: temples, villages & maritime power",
    "c. 850–13th century CE",
    "Connect military expansion with irrigation, temple institutions and local administration in southern India.",
    [
      "Distinguish Rajaraja I and Rajendra I.",
      "Connect Thanjavur and Gangaikondacholapuram with royal patronage.",
      "Study village assemblies and overseas connections alongside campaigns.",
    ],
    [r("sultanate", 112, 126)],
    ["sangam", "vijayanagara"],
  ),
  t(
    "turkish-conquests",
    "regional",
    "Sindh, Ghazni & Ghur",
    "8th–12th centuries CE",
    "Separate the conquest of Sindh, Ghaznavid raids and Ghurid territorial expansion.",
    [
      "Muhammad bin Qasim is associated with the conquest of Sindh.",
      "Distinguish Mahmud of Ghazni from Muhammad of Ghur.",
      "Compare the two battles of Tarain, 1191 and 1192, and the road to the Sultanate.",
    ],
    [r("sultanate", 30, 40)],
    ["mamluks"],
  ),
  t(
    "mamluks",
    "sultanate",
    "Mamluks: founding the Delhi Sultanate",
    "1206–1290",
    "Follow the consolidation of Delhi under Aibak, Iltutmish, Razia and Balban.",
    [
      "Learn the functions of iqta assignments and the Turkish nobility.",
      "Distinguish the initiation and completion of Qutb Minar.",
      "Compare Iltutmish’s consolidation with Balban’s conception of kingship.",
    ],
    [r("sultanate", 41, 63)],
    ["khaljis"],
  ),
  t(
    "khaljis",
    "sultanate",
    "Khaljis: expansion & market reforms",
    "1290–1320",
    "Link Alauddin’s military needs with taxation, market regulation and administrative control.",
    [
      "Distinguish Jalaluddin from Alauddin.",
      "Connect Malik Kafur with Deccan expeditions.",
      "Explain how controlled prices and army organisation supported a standing army.",
    ],
    [r("sultanate", 64, 83)],
    ["tughlaqs", "mughal-administration"],
  ),
  t(
    "tughlaqs",
    "sultanate",
    "Tughlaqs: experiments & public works",
    "1320–1414",
    "Compare Muhammad bin Tughlaq’s ambitious experiments with Firoz Shah’s administrative policies.",
    [
      "Capital transfer, token currency and Doab taxation require separate explanations.",
      "Assess intended purposes as well as implementation failures.",
      "Connect Firoz Shah with canals, departments and hereditary tendencies.",
    ],
    [r("sultanate", 84, 100)],
    ["later-sultanate", "bahmani"],
  ),
  t(
    "later-sultanate",
    "sultanate",
    "Sayyids, Lodis & the end of the Sultanate",
    "1414–1526",
    "Trace weakening central authority, Afghan rule and the transition to Mughal power.",
    [
      "Sequence Khizr Khan, Bahlul Lodi, Sikandar Lodi and Ibrahim Lodi.",
      "Associate Sikandar Lodi with Agra.",
      "The first battle of Panipat in 1526 links the Lodi and Mughal narratives.",
    ],
    [r("sultanate", 101, 111)],
    ["babur"],
  ),
  t(
    "vijayanagara",
    "sultanate",
    "Vijayanagara: a southern imperial centre",
    "From 1336",
    "Study the Sangama, Saluva, Tuluva and Aravidu dynasties through political rivalry, trade and cultural patronage.",
    [
      "Harihara and Bukka founded the kingdom.",
      "Connect Krishnadevaraya with the Tuluva dynasty and literary patronage.",
      "Talikota in 1565 devastated the capital; the polity continued under successors.",
    ],
    [r("sultanate", 127, 149)],
    ["bahmani", "cholas"],
  ),
  t(
    "bahmani",
    "sultanate",
    "Bahmani kingdom & Deccan sultanates",
    "1347 onward",
    "Connect Deccan politics with conflict, court factions and Mahmud Gawan’s reforms.",
    [
      "Hasan Gangu founded the Bahmani kingdom.",
      "Study tarafs, the capital at Bidar and Mahmud Gawan’s madrasa.",
      "Name the five successor sultanates and locate them.",
    ],
    [r("sultanate", 150, 164)],
    ["vijayanagara", "akbar-expansion"],
  ),
  t(
    "babur",
    "mughal",
    "Babur & the founding battles",
    "1526–1530",
    "Build a short sequence of Panipat, Khanwa, Chanderi and Ghaghra to understand the foundations of Mughal power.",
    [
      "Panipat: Babur defeated Ibrahim Lodi in 1526.",
      "Khanwa: conflict with Rana Sanga in 1527.",
      "Consider artillery, military organisation and alliances together.",
    ],
    [r("mughals", 1, 8)],
    ["later-sultanate", "humayun"],
  ),
  t(
    "humayun",
    "mughal",
    "Humayun & Sher Shah Suri",
    "1530–1556",
    "Compare Mughal displacement and restoration with the short but influential Sur administration.",
    [
      "Chausa and Kannauj mark Humayun’s defeats by Sher Shah.",
      "Humayun regained Delhi in 1555.",
      "Connect Sher Shah with roads, sarais, revenue organisation and the rupiya.",
    ],
    [r("mughals", 9, 22)],
    ["akbar-expansion"],
  ),
  t(
    "akbar-expansion",
    "mughal",
    "Akbar: consolidation & alliances",
    "1556–1605",
    "Organise Akbar’s expansion geographically and relate conquest to negotiation with regional elites.",
    [
      "The second battle of Panipat was fought against Hemu in 1556.",
      "Study Rajput alliances alongside the resistance of Mewar.",
      "Locate Gujarat, Bengal, the northwest and the Deccan on the expansion map.",
    ],
    [r("mughals", 23, 58)],
    ["mughal-administration", "akbar-culture"],
  ),
  t(
    "mughal-administration",
    "mughal",
    "Mughal administration & land revenue",
    "Akbar and successors",
    "Connect central offices with provincial government and revenue assessment.",
    [
      "Distinguish diwan, mir bakshi, mir saman and qazi.",
      "Sequence suba → sarkar → pargana → village.",
      "Explain zabt, dahsala, land classification and revenue collection.",
    ],
    [r("mughals", 59, 82)],
    ["mansab-jagir", "revenue-colonial"],
  ),
  t(
    "mansab-jagir",
    "mughal",
    "Mansabdari, jagirs & zamindars",
    "Mughal institutions",
    "Keep rank, military obligation, revenue assignment and local rights distinct.",
    [
      "Zat indicates personal rank; sawar indicates the cavalry obligation.",
      "A jagir was a revenue assignment, not automatic ownership of the land.",
      "Compare mansabdars, jagirdars and zamindars without treating the labels as synonyms.",
    ],
    [r("mughals", 83, 95)],
    ["mughal-administration", "mughal-decline"],
  ),
  t(
    "akbar-culture",
    "mughal",
    "Akbar: dialogue, patronage & policy",
    "16th century",
    "Study religious discussion and imperial inclusion alongside literary and artistic patronage.",
    [
      "Associate the Ibadat Khana with Fatehpur Sikri.",
      "Explain sulh-i kul as an approach to peace and inclusion.",
      "Distinguish Abul Fazl, Faizi, Tansen, Birbal and Todar Mal.",
    ],
    [r("mughals", 96, 105)],
    ["jahangir", "bhakti-sufi"],
  ),
  t(
    "jahangir",
    "mughal",
    "Jahangir & Shah Jahan",
    "1605–1658",
    "Compare court politics, diplomatic contacts and artistic patronage under two emperors.",
    [
      "Study Nur Jahan’s political role.",
      "Connect Thomas Roe with Jahangir’s court.",
      "Associate Shah Jahan with major architectural projects and the succession conflict.",
    ],
    [r("mughals", 106, 121)],
    ["aurangzeb", "europeans"],
  ),
  t(
    "aurangzeb",
    "mughal",
    "Aurangzeb: policy & resistance",
    "1658–1707",
    "Examine imperial policies and opposition within their political context; avoid reducing the reign to a single cause or identity.",
    [
      "Trace relations with Rajputs, Sikhs and the Marathas.",
      "Distinguish religious policy, fiscal pressures and military expansion.",
      "Build a multi-causal explanation of the strains on imperial government.",
    ],
    [r("mughals", 122, 130)],
    ["mughal-decline"],
  ),
  t(
    "europeans",
    "colonial",
    "European trading companies",
    "1498–18th century",
    "Compare Portuguese, Dutch, English, Danish and French settlements and strategies.",
    [
      "Vasco da Gama reached Calicut in 1498.",
      "Learn the English company charter of 1600 and early trading contacts.",
      "Locate settlements and connect sea power with commercial competition.",
    ],
    [r("modern", 1, 10)],
    ["carnatic", "jahangir"],
  ),
  t(
    "carnatic",
    "colonial",
    "Carnatic wars & European rivalry",
    "1746–1763",
    "Connect conflicts in Europe with succession struggles and European intervention in southern India.",
    [
      "Distinguish the three Carnatic wars and their settlements.",
      "Compare Dupleix’s strategy and English company intervention.",
      "Wandiwash in 1760 weakened French military prospects in India.",
    ],
    [r("modern", 14, 16), r("mains-1", 1, 5), r("mains-1", 12)],
    ["bengal"],
  ),
  t(
    "bengal",
    "colonial",
    "Plassey, Buxar & the diwani",
    "1757–1772",
    "Explain the transition from commercial privileges to control over revenue and government.",
    [
      "Plassey in 1757 and Buxar in 1764 had different opponents and consequences.",
      "The grant of diwani in 1765 gave the Company revenue rights in Bengal, Bihar and Orissa.",
      "Separate dual government in Bengal from later dual control in Britain.",
    ],
    [r("modern", 17, 20), r("mains-1", 24, 42)],
    ["company-acts", "revenue-colonial"],
  ),
  t(
    "mysore-marathas",
    "colonial",
    "Mysore, Marathas & British expansion",
    "1761–1818",
    "Follow regional resistance and changing alliances without treating British expansion as inevitable.",
    [
      "Third Panipat: Marathas faced Ahmad Shah Abdali in 1761.",
      "Compare four Anglo-Mysore wars, their treaties and Tipu Sultan’s defeat in 1799.",
      "Sequence the Anglo-Maratha wars and the role of the Treaty of Bassein.",
    ],
    [r("modern", 21, 26), r("mains-1", 6, 11), r("mains-1", 13, 23)],
    ["annexation"],
  ),
  t(
    "annexation",
    "colonial",
    "Subsidiary alliance & doctrine of lapse",
    "Late 18th–mid-19th century",
    "Compare two mechanisms of expansion and their effects on princely autonomy.",
    [
      "Associate Wellesley with subsidiary alliances.",
      "Associate Dalhousie with the doctrine of lapse.",
      "Do not classify every annexation as lapse: Awadh was annexed on a claim of misgovernment.",
    ],
    [r("modern", 70, 74), r("mains-1", 43, 52)],
    ["revolt-1857", "integration"],
  ),
  t(
    "company-acts",
    "colonial",
    "Company rule & constitutional change",
    "1773–1858",
    "Build an act–provision–consequence table, tracking how Parliament increased supervision of the Company.",
    [
      "Regulating Act 1773; Pitt’s India Act 1784.",
      "Compare the Charter Acts of 1813, 1833 and 1853.",
      "The 1858 transfer to the Crown followed the revolt.",
    ],
    [r("mains-1", 53, 77)],
    ["constitutional-reforms"],
  ),
  t(
    "revenue-colonial",
    "colonial",
    "Land revenue & colonial economy",
    "Late 18th–19th century",
    "Compare who paid revenue, whether assessments were permanent, and how each arrangement affected cultivators.",
    [
      "Permanent Settlement: revenue fixed with zamindars in Bengal in 1793.",
      "Ryotwari: settlement with cultivators; Mahalwari: village/estate units.",
      "For mains, connect demands and intermediaries to agrarian distress and economic change.",
    ],
    [r("modern", 11, 13), r("mains-2", 1, 4)],
    ["bengal", "mughal-administration", "colonial-economy"],
  ),
  t(
    "governors",
    "colonial",
    "Governors-general & viceroys",
    "1772–1947 · reference track",
    "Use a parallel reference track to connect policies and events to administrations. Study the events first, then practise matching them.",
    [
      "Separate Governors-General of Bengal, Governors-General of India and viceroys.",
      "Group policies by education, communication, administration and repression.",
      "Cross-check dates in this deck before turning every statement into a flashcard.",
    ],
    [r("modern", 27, 65), r("mains-1", 74)],
    ["company-acts", "constitutional-reforms"],
  ),
  t(
    "revolt-1857",
    "colonial",
    "The revolt of 1857",
    "1857–1858",
    "Build a causes → centres and leaders → limits → consequences answer, distinguishing long-term grievances from the immediate trigger.",
    [
      "Political annexation, economic pressures, military grievances and religious fears overlapped.",
      "Match Delhi, Kanpur, Lucknow, Jhansi and Bihar with key leaders.",
      "Assess regional variation and why the rebellion failed; connect it to Crown rule.",
    ],
    [r("modern", 66, 69), r("mains-1", 78, 100)],
    ["annexation", "company-acts"],
  ),
  t(
    "reform-bengal",
    "colonial",
    "Bengal reform & modern education",
    "19th century",
    "Study reformers’ arguments, institutions and social limits rather than memorising founders alone.",
    [
      "Connect Rammohun Roy with the Brahmo tradition.",
      "Compare Derozio, Debendranath Tagore and Keshab Chandra Sen.",
      "Link Vidyasagar to widow remarriage and education; compare reform methods.",
    ],
    [r("modern", 75, 80), r("mains-1", 101, 130)],
    ["reform-west", "early-associations"],
  ),
  t(
    "reform-west",
    "colonial",
    "Reform, caste & religious renewal",
    "19th–early 20th century",
    "Compare movements across regions through education, gender, caste, scriptural authority and public service.",
    [
      "Connect Phule with Satyashodhak Samaj and Dayanand with Arya Samaj.",
      "Compare Prarthana Samaj, Ramakrishna Mission and the Theosophical Society.",
      "Study Muslim, Sikh and Parsi reform movements and the limits of reform’s social reach.",
    ],
    [r("modern", 81, 87), r("mains-1", 131, 184)],
    ["reform-bengal", "women-students"],
  ),
  t(
    "early-associations",
    "colonial",
    "Political associations before Congress",
    "1830s–1885",
    "Trace the growth of public associations, political demands and communication across regions.",
    [
      "Distinguish the British Indian Association and Indian Association.",
      "Locate Poona Sarvajanik Sabha, Madras Mahajan Sabha and Bombay Presidency Association.",
      "Connect early political methods with the founding of Congress.",
    ],
    [r("modern", 88, 90), r("mains-2", 5, 27)],
    ["congress"],
  ),
  t(
    "congress",
    "freedom",
    "Congress, moderates & assertive nationalism",
    "1885–1907",
    "Compare goals, social bases and methods of early nationalists, then explain the tensions that culminated at Surat.",
    [
      "The first Congress session in 1885 was presided over by W. C. Bonnerjee.",
      "Contrast petitions and economic critique with boycott and wider mobilisation.",
      "Treat “safety valve” as a historical interpretation, not an uncontested single cause.",
    ],
    [r("modern", 91, 97), r("modern", 104), r("mains-2", 28, 49)],
    ["swadeshi", "early-associations"],
  ),
  t(
    "swadeshi",
    "freedom",
    "Bengal partition, Swadeshi & boycott",
    "1905–1911",
    "Connect the partition of Bengal with new forms of protest, economic self-reliance and national education.",
    [
      "The partition took effect on 16 October 1905.",
      "Compare boycott, indigenous industry, national education and passive resistance.",
      "Assess participation, repression, limitations and the annulment in 1911.",
    ],
    [r("modern", 98, 102), r("mains-2", 50), r("freedom", 1, 25)],
    ["congress", "non-cooperation"],
  ),
  t(
    "league-revolutionaries",
    "freedom",
    "Muslim League, Ghadar & overseas politics",
    "1906–1916",
    "Study different political organisations and overseas networks with attention to their changing demands.",
    [
      "Muslim League was founded at Dacca in 1906.",
      "Ghadar connected emigrant revolutionaries to an anti-colonial project.",
      "Place Komagata Maru in 1914 and distinguish it from the Home Rule leagues.",
    ],
    [
      r("modern", 103),
      r("modern", 107, 108),
      r("mains-2", 51, 53),
      r("mains-2", 64, 67),
    ],
    ["home-rule", "partition-negotiations"],
  ),
  t(
    "home-rule",
    "freedom",
    "Home Rule & the Lucknow Pact",
    "1916–1917",
    "Connect the wartime demand for self-government with Congress reunification and Congress–League cooperation.",
    [
      "Separate Tilak’s and Annie Besant’s Home Rule leagues.",
      "Lucknow Pact belongs to 1916.",
      "Place the August Declaration in 1917 within the reform debate.",
    ],
    [r("modern", 109, 112), r("mains-2", 68, 76)],
    ["constitutional-reforms", "gandhi-early"],
  ),
  t(
    "constitutional-reforms",
    "freedom",
    "Reforms, representation & dyarchy",
    "1909–1935",
    "Compare constitutional arrangements by electorate, provincial powers and control at the centre.",
    [
      "1909: separate electorates for Muslims.",
      "1919: dyarchy in the provinces.",
      "1935: provincial autonomy; the proposed all-India federation did not come into operation.",
    ],
    [
      r("modern", 105, 106),
      r("modern", 113),
      r("modern", 149),
      r("mains-2", 54, 63),
      r("mains-2", 77, 87),
      r("mains-2", 132),
    ],
    ["company-acts", "poona-pact"],
  ),
  t(
    "gandhi-early",
    "freedom",
    "Gandhi: early satyagrahas & 1919",
    "1917–1919",
    "Compare local struggles before following the expansion of protest against the Rowlatt Act.",
    [
      "Champaran: indigo cultivators; Ahmedabad: mill workers; Kheda: revenue relief.",
      "Satyagraha combines truth and non-violent resistance.",
      "Explain the Rowlatt agitation and Jallianwala Bagh in their 1919 context.",
    ],
    [r("modern", 114, 119), r("mains-2", 88, 97)],
    ["non-cooperation", "bardoli"],
  ),
  t(
    "non-cooperation",
    "freedom",
    "Khilafat & Non-Cooperation",
    "1919–1922",
    "Explain the convergence of grievances, the boycott programme and the decision to suspend the movement.",
    [
      "Connect Khilafat, Punjab grievances and disillusionment with reforms.",
      "Distinguish withdrawal of cooperation from later deliberate law-breaking.",
      "Chauri Chaura in February 1922 prompted suspension.",
    ],
    [r("modern", 120, 125), r("mains-2", 98, 104), r("freedom", 26, 53)],
    ["swadeshi", "swarajists", "civil-disobedience"],
  ),
  t(
    "swarajists",
    "freedom",
    "Swarajists, Simon & the Nehru Report",
    "1922–1929",
    "Follow the debate over council entry and the competing proposals for constitutional advance.",
    [
      "C. R. Das and Motilal Nehru led the Swarajist approach.",
      "The all-British Simon Commission was appointed in 1927 and arrived in 1928.",
      "Contrast the Nehru Report, Jinnah’s Fourteen Points and the Lahore resolution.",
    ],
    [r("modern", 126, 136), r("mains-2", 105, 113), r("mains-2", 119, 122)],
    ["civil-disobedience"],
  ),
  t(
    "bardoli",
    "freedom",
    "Bardoli & agrarian satyagraha",
    "1928",
    "Examine how local organisation and disciplined protest challenged an increased revenue assessment.",
    [
      "Locate Bardoli in Gujarat.",
      "Associate the movement with Vallabhbhai Patel.",
      "Compare its revenue issue and methods with Kheda.",
    ],
    [r("mains-2", 114, 118)],
    ["gandhi-early", "integration"],
  ),
  t(
    "civil-disobedience",
    "freedom",
    "Civil Disobedience & the salt campaign",
    "1930–1934",
    "Connect Purna Swaraj with salt law-breaking, regional participation, negotiations and renewed repression.",
    [
      "Dandi made an everyday tax a widely understood political issue.",
      "Compare participation and limitations with Non-Cooperation.",
      "Sequence Gandhi–Irwin Pact, the conferences and the resumption of protest.",
    ],
    [
      r("modern", 137, 144),
      r("modern", 148),
      r("mains-2", 123, 127),
      r("mains-2", 131),
      r("freedom", 54, 74),
    ],
    ["non-cooperation", "poona-pact"],
  ),
  t(
    "poona-pact",
    "freedom",
    "Communal Award & the Poona Pact",
    "1932",
    "Separate the question of separate electorates from reserved representation, and recognise Ambedkar’s political role.",
    [
      "The Communal Award proposed separate electorates for the Depressed Classes.",
      "The Poona Pact used reserved seats within a joint electorate.",
      "Compare the positions of Gandhi and Ambedkar without collapsing their aims.",
    ],
    [r("modern", 145, 147), r("mains-2", 128, 130)],
    ["constitutional-reforms", "ambedkar"],
  ),
  t(
    "war-quit-india",
    "freedom",
    "Wartime proposals & Quit India",
    "1939–1942",
    "Study the relationship between wartime pressures, failed negotiations and the demand for an immediate British withdrawal.",
    [
      "Sequence August Offer, Individual Satyagraha and Cripps Mission.",
      "The Quit India resolution was adopted in August 1942.",
      "Assess underground networks, local initiatives, repression and limits of participation.",
    ],
    [r("modern", 150, 160), r("mains-2", 133, 139), r("freedom", 75, 90)],
    ["ina", "partition-negotiations"],
  ),
  t(
    "ina",
    "freedom",
    "Subhas Chandra Bose & the INA",
    "1940s",
    "Trace the formation, reorganisation and political significance of the Indian National Army.",
    [
      "Distinguish the early INA associated with Mohan Singh from Bose’s later leadership.",
      "Connect the Azad Hind government with the wartime context.",
      "Explain the significance of the Red Fort trials without claiming a single cause for independence.",
    ],
    [r("modern", 166, 168)],
    ["war-quit-india"],
  ),
  t(
    "partition-negotiations",
    "freedom",
    "Negotiations, partition & independence",
    "1940–1947",
    "Follow competing proposals and their failures through to the transfer of power and its human consequences.",
    [
      "Sequence Lahore Resolution, Rajagopalachari formula, Wavell Plan and Cabinet Mission.",
      "Distinguish the 1946 Cabinet Mission from the 1947 Mountbatten Plan.",
      "Connect independence and partition to administrative division and displacement.",
    ],
    [r("modern", 161, 165), r("modern", 169, 176), r("mains-2", 140, 152)],
    ["partition-rehab", "integration"],
  ),
  t(
    "women-students",
    "freedom",
    "Women, students & mass participation",
    "Across the freedom struggle",
    "Build a thematic answer across movements instead of treating participation as a single-event appendix.",
    [
      "Connect women’s roles with boycott, picketing, underground activity and leadership.",
      "Trace students’ involvement in national education and protest.",
      "Assess how mobilisation challenged social roles and where exclusions persisted.",
    ],
    [r("freedom", 91, 99)],
    ["swadeshi", "war-quit-india", "reform-west"],
  ),
  t(
    "partition-rehab",
    "republic",
    "Partition & rehabilitation",
    "1947 and aftermath",
    "Organise humanitarian, administrative, economic and political consequences of partition.",
    [
      "Displacement and violence created urgent rehabilitation needs.",
      "Division affected services, assets, trade and production networks.",
      "Avoid presenting a single disputed casualty estimate as a settled fact.",
    ],
    [r("republic", 1, 4)],
    ["partition-negotiations", "integration"],
  ),
  t(
    "integration",
    "republic",
    "Integration of princely states",
    "1947–1949",
    "Compare negotiation, accession, merger and military intervention in the formation of the Union.",
    [
      "Study the roles of Vallabhbhai Patel and V. P. Menon.",
      "Accession initially concerned defence, external affairs and communications.",
      "Compare Travancore, Jodhpur, Bhopal, Hyderabad and Junagadh as distinct cases.",
    ],
    [r("republic", 11, 17), r("republic", 26, 41)],
    ["states-reorganisation", "kashmir", "annexation"],
  ),
  t(
    "states-reorganisation",
    "republic",
    "Linguistic reorganisation & new states",
    "1950s onward",
    "Explain how language, administration, democratic demands and national unity interacted in redrawing state boundaries.",
    [
      "Distinguish Part A/B/C/D states and later states/Union territories.",
      "Andhra State was formed in 1953; Andhra Pradesh followed in 1956.",
      "Sequence Dhar Commission, JVP Committee and the States Reorganisation Commission.",
    ],
    [r("republic", 5, 10), r("republic", 18, 25)],
    ["integration", "northeast"],
  ),
  t(
    "kashmir",
    "republic",
    "Jammu & Kashmir: accession chronology",
    "1947 onward",
    "Build a dated sequence from the accession crisis using primary documents and clearly attributed historical accounts.",
    [
      "Identify Hari Singh and the Instrument of Accession.",
      "Distinguish accession, subsequent constitutional arrangements and later changes.",
      "The deck compresses contested events and legal developments; check authoritative sources before adding detailed MCQs.",
    ],
    [r("republic", 42, 46)],
    ["integration"],
  ),
];

// Explicit gaps are part of the coverage map, not silently counted as completed lessons.
const gaps = [
  [
    "bhakti-sufi",
    "sultanate",
    "Bhakti, Sufism & regional cultural traditions",
    "Medieval India",
    "The 2025 question set asks about Bhakti; the teaching decks do not supply a dedicated lesson.",
    [
      "Alvars and Nayanars; saguna and nirguna traditions",
      "Kabir, Nanak, regional saints and vernacular literature",
      "Sufi silsilas, khanqahs, social context and composite culture",
    ],
    ["akbar-culture"],
  ],
  [
    "mughal-decline",
    "mughal",
    "Later Mughals, Marathas & successor states",
    "1707–18th century",
    "Add a bridge between Aurangzeb and Company expansion.",
    [
      "Maratha state formation and Shivaji’s administration",
      "Regional successor states and changing revenue networks",
      "Multiple explanations for Mughal decline",
    ],
    ["aurangzeb", "mysore-marathas"],
  ],
  [
    "colonial-economy",
    "colonial",
    "Economic change, education & cultural consciousness",
    "18th–20th century",
    "Past questions require fuller coverage than the revenue-system notes provide.",
    [
      "Drain of wealth, deindustrialisation and commercialisation",
      "Western education, print, historical writing and cultural revival",
      "Peasant and tribal resistance with regional examples",
    ],
    ["revenue-colonial", "reform-bengal"],
  ],
  [
    "ambedkar",
    "republic",
    "Ambedkar, the Constitution & democracy",
    "20th century",
    "The mains questions ask about Ambedkar; a dedicated lesson remains to be authored.",
    [
      "Social justice and political representation",
      "Constituent Assembly and constitution-making",
      "Universal adult franchise and the first general election",
    ],
    ["poona-pact"],
  ],
  [
    "planning",
    "republic",
    "Planning, development & foreign policy",
    "After 1947",
    "The past-paper deck asks about Five-Year Plans, but the teaching deck concentrates on integration.",
    [
      "Planning and the mixed economy",
      "Land reforms and the Green Revolution",
      "Non-alignment, major conflicts and political change",
    ],
    ["states-reorganisation"],
  ],
  [
    "northeast",
    "republic",
    "Northeast India & Mizoram",
    "Regional extension",
    "Add dedicated coverage for Mizoram exam preparation and check the current official syllabus.",
    [
      "Regional state formation and political movements",
      "Mizoram: historical milestones, peace accord and statehood",
      "Connections to post-independence reorganisation",
    ],
    ["states-reorganisation"],
  ],
  [
    "industrial-world",
    "world",
    "Industrial Revolution, capitalism & colonialism",
    "18th–20th century",
    "These themes recur in the supplied mains questions; teaching notes are absent.",
    [
      "Why industrialisation began in Britain",
      "Economic and social consequences of industrialisation",
      "Colonialism and its effects on colonised societies",
    ],
    ["colonial-economy"],
  ],
  [
    "wars-world",
    "world",
    "World wars, fascism & the United Nations",
    "1914–1945 and aftermath",
    "Preserve these past-paper demands as visible gaps in the learning path.",
    [
      "First World War: alliances, causes and consequences",
      "Fascism, Nazism and the road to the Second World War",
      "United Nations: origins, aims, structure and achievements",
    ],
    ["war-quit-india"],
  ],
  [
    "ideologies-world",
    "world",
    "Socialism, decolonisation & the Cold War",
    "20th century",
    "Past questions cover themes beyond the Indian-history lecture decks.",
    [
      "Communism, socialism and capitalism: distinctions",
      "Decolonisation in Asia and Africa",
      "Soviet collapse, Eastern Europe and post-Mao China",
    ],
    ["industrial-world"],
  ],
];
for (const [id, era, title, period, summary, checkpoints, related] of gaps)
  topics.push(
    t(id, era, title, period, summary, checkpoints, [], related, "gap"),
  );

export const reviews = [
  {
    id: "harappa-dates",
    topicId: "harappa",
    sourceId: "ancient",
    slide: 10,
    status: "corrected",
    note: "The deck heading gives 2600–1500 BCE. Use c. 2600–1900 BCE specifically for the Mature Harappan urban phase; distinguish earlier and later phases.",
    evidence: [
      {
        title: "NCERT · Bricks, Beads and Bones, p. 1",
        url: "https://ncert.nic.in/textbook/pdf/lehs101.pdf",
      },
    ],
  },
  {
    id: "prarthana-date",
    topicId: "reform-west",
    sourceId: "mains-1",
    slide: 144,
    status: "corrected",
    note: "This slide labels Prarthana Samaj 1876. The foundation at Bombay was in 1867.",
    evidence: [
      {
        title: "Municipal Corporation of Greater Mumbai · Prarthana Samaj",
        url: "https://www.mcgm.gov.in/irj/go/km/docs/documents/D%20Ward/Heritage-Sites/86_Legacy%20of%20D%20Ward_Article_Prarthana%20Samaj.pdf",
      },
    ],
  },
  {
    id: "andhra-name",
    topicId: "states-reorganisation",
    sourceId: "republic",
    slide: 21,
    status: "corrected",
    note: "Distinguish Andhra State (1953) from Andhra Pradesh (1956). The slide uses Andhra Pradesh for the 1953 formation.",
    evidence: [
      {
        title: "Andhra State Act, 1953",
        url: "https://www.indiacode.nic.in/bitstream/123456789/2176/1/195330.pdf",
      },
      {
        title: "Andhra Pradesh PSC · History",
        url: "https://portal-psc.ap.gov.in/HomePages/History",
      },
    ],
  },
  {
    id: "rashtrakuta-dates",
    topicId: "tripartite",
    sourceId: "sultanate",
    slide: 29,
    status: "open",
    note: "The Krishna III reign dates printed here need verification. This item is excluded from the quiz bank.",
    evidence: [],
  },
  {
    id: "chola-dates",
    topicId: "cholas",
    sourceId: "sultanate",
    slide: 115,
    status: "open",
    note: "Parantaka I has the same printed date range as Sundara Chola on the next slide. Verify the chronology before generating date questions.",
    evidence: [],
  },
  {
    id: "gupta-generalisation",
    topicId: "gupta",
    sourceId: "ancient",
    slide: 130,
    status: "open",
    note: "The absolute claim about the absence of Buddhist royal patronage needs review. Do not convert it into an answer key.",
    evidence: [],
  },
  {
    id: "poona-seats",
    topicId: "poona-pact",
    sourceId: "modern",
    slide: 147,
    status: "corrected",
    note: "The Poona Pact provided 148 provincial reserved seats, not the printed 147, within a joint-electorate arrangement with a preliminary selection by Depressed Class voters.",
    evidence: [
      {
        title: "Ministry of External Affairs · archival documents, Volume 10",
        url: "https://www.mea.gov.in/Images/CPV/Volume10.pdf",
      },
    ],
  },
  {
    id: "poona-seats-mains",
    topicId: "poona-pact",
    sourceId: "mains-2",
    slide: 130,
    status: "corrected",
    note: "The provincial reserved-seat total was 148, not 147. Reserved seats were within joint electorates; distinguish this from the separate electorates in the Communal Award.",
    evidence: [
      {
        title: "Ministry of External Affairs · archival documents, Volume 10",
        url: "https://www.mea.gov.in/Images/CPV/Volume10.pdf",
      },
    ],
  },
  {
    id: "poona-date",
    topicId: "poona-pact",
    sourceId: "mains-2",
    slide: 129,
    status: "corrected",
    note: "The pact was concluded on 24 September 1932, rather than the printed 25 September.",
    evidence: [
      {
        title: "Museums of India · Pune Pact, 24 September 1932",
        url: "https://museumsofindia.gov.in/repository/record/avm_pun-P0019-441",
      },
    ],
  },
  {
    id: "sarojini-session",
    topicId: "congress",
    sourceId: "modern",
    slide: 93,
    status: "corrected",
    note: "Sarojini Naidu presided over the Kanpur Congress session in 1925, not 1923.",
    evidence: [
      {
        title: "Museums of India · Sarojini Naidu",
        url: "https://museumsofindia.gov.in/repository/record/vmh_kol-R3177-18169",
      },
    ],
  },
];

export const metadata = {
  schemaVersion: 1,
  version: "1.0.0",
  title: "History Learning Atlas",
  description:
    "A structured first pass through nine supplied MS Academy presentations. Source text is preserved; lesson checkpoints and practice MCQs are derived study aids, not an official answer key.",
  reviewedOn: "2026-10-07",
  syllabusStatus:
    "Organised from the supplied presentations and their mains question list; not audited against a current official examination syllabus.",
};
