// Authoring input: id, topic, stem, four options, 0-based answer, explanation,
// sourceId, slide, difficulty (optional). These are original practice questions,
// derived from the supplied material. They are NOT official past-paper MCQs.
const q = (
  id,
  topicId,
  prompt,
  options,
  answerIndex,
  explanation,
  sourceId,
  slide,
  difficulty = "foundation",
) => ({
  id,
  revision: 1,
  topicId,
  prompt,
  options,
  answerIndex,
  explanation,
  sources: [{ sourceId, from: slide, to: slide }],
  difficulty,
  provenance: "derived",
  reviewStatus: "source-checked",
});

export const questions = [
  q(
    "h001",
    "prehistory",
    "Microliths are particularly associated with which archaeological phase?",
    ["Mesolithic", "Mature Harappan", "Mauryan", "Gupta"],
    0,
    "Microliths are small stone tools associated with Mesolithic assemblages. The other options refer to much later urban or political periods.",
    "ancient",
    5,
  ),
  q(
    "h002",
    "prehistory",
    "Which combination best distinguishes Neolithic life from earlier hunting-and-gathering patterns?",
    [
      "Iron currency and imperial taxation",
      "Farming, domestication and polished stone tools",
      "Gunpowder and cavalry",
      "Printing and factory production",
    ],
    1,
    "Farming, domestication and polished stone tools are key Neolithic developments. Their adoption varied by region and did not happen everywhere at once.",
    "ancient",
    6,
  ),
  q(
    "h003",
    "harappa",
    "The Great Bath is associated with which Harappan site?",
    ["Harappa", "Lothal", "Mohenjodaro", "Kalibangan"],
    2,
    "The Great Bath was excavated at Mohenjodaro. A site–find table helps distinguish urban features across Harappan settlements.",
    "ancient",
    24,
  ),
  q(
    "h004",
    "harappa",
    "Which statement about the Harappan script is the safest historical conclusion?",
    [
      "It is a fully translated Sanskrit alphabet",
      "It is identical to Ashokan Brahmi",
      "It has been conclusively read as Tamil",
      "It remains undeciphered",
    ],
    3,
    "The Harappan script remains undeciphered. Proposed linguistic identifications should not be confused with an established decipherment.",
    "ancient",
    35,
  ),
  q(
    "h005",
    "harappa",
    "Which pair consists of materials used in the alloy bronze?",
    ["Copper and tin", "Iron and carbon", "Gold and silver", "Lead and zinc"],
    0,
    "Bronze is an alloy of copper and tin. The slide discusses bronze tools in the Harappan material record.",
    "ancient",
    29,
  ),
  q(
    "h006",
    "vedic-early",
    "In the early Vedic context, the term rajan referred primarily to the:",
    [
      "Chief revenue accountant",
      "Tribal chief",
      "Head of a guild",
      "Buddhist monk",
    ],
    1,
    "Rajan referred to the tribal chief. It should be understood within early Vedic kinship-based polity, not automatically as a later territorial emperor.",
    "ancient",
    45,
  ),
  q(
    "h007",
    "vedic-early",
    "Which activity was especially important in the early Vedic economy?",
    [
      "Oceanic factory trade",
      "Plantation tea cultivation",
      "Pastoralism",
      "Industrial mining",
    ],
    2,
    "Cattle and pastoral life held particular importance in early Vedic society; agriculture also existed. Later Vedic study brings the greater importance of agriculture into focus.",
    "ancient",
    43,
  ),
  q(
    "h008",
    "vedic-later",
    "Which change is associated with the later Vedic period in these notes?",
    [
      "Agriculture disappeared",
      "Assemblies gained unlimited control over kings",
      "Territorial organisation ceased to exist",
      "Agriculture became more central to the economy",
    ],
    3,
    "The notes describe agriculture becoming the principal economic activity and political organisation becoming more territorial.",
    "ancient",
    54,
  ),
  q(
    "h009",
    "vedic-texts",
    "Which Veda is especially associated with melodies and chants?",
    ["Sama Veda", "Yajur Veda", "Atharva Veda", "Rig Veda"],
    0,
    "Sama Veda is associated with chants and melodies. Rig Veda contains hymns; Yajur Veda centres on sacrificial formulae.",
    "ancient",
    61,
  ),
  q(
    "h010",
    "vedic-texts",
    "The Upanishads are most closely associated with:",
    [
      "Lists of Mughal ranks",
      "Philosophical inquiry",
      "Colonial revenue surveys",
      "Sultanate market prices",
    ],
    1,
    "The Upanishads develop philosophical discussions. Brahmanas are especially associated with explanations of sacrificial rituals.",
    "ancient",
    66,
  ),
  q(
    "h011",
    "mahajanapadas",
    "Which dynasty did Chandragupta Maurya overthrow in Magadha?",
    ["Gupta", "Pala", "Nanda", "Chola"],
    2,
    "The Mauryan rise followed the overthrow of the Nanda ruler. Keep this transition separate from the much later Gupta period.",
    "ancient",
    75,
  ),
  q(
    "h012",
    "mahajanapadas",
    "Bimbisara belonged to which dynasty?",
    ["Shunga", "Kushan", "Gupta", "Haryanka"],
    3,
    "Bimbisara was a Haryanka ruler of Magadha. Shishunaga and Nanda rule followed later.",
    "ancient",
    70,
  ),
  q(
    "h013",
    "buddhism",
    "Which set gives the three jewels of Buddhism?",
    [
      "Buddha, dhamma, sangha",
      "Right faith, knowledge, conduct",
      "Brahma, Vishnu, Shiva",
      "Rajan, sabha, samiti",
    ],
    0,
    "Buddha, dhamma and sangha are the Buddhist three jewels. Right faith, knowledge and conduct are the Jain three jewels.",
    "ancient",
    81,
  ),
  q(
    "h014",
    "buddhism",
    "The Milindapanho is associated with a dialogue between:",
    [
      "Ashoka and Kautilya",
      "Menander and Nagasena",
      "Akbar and Abul Fazl",
      "Harsha and Banabhatta",
    ],
    1,
    "Milindapanho presents a dialogue between the Indo-Greek ruler Menander (Milinda) and the Buddhist monk Nagasena.",
    "ancient",
    84,
  ),
  q(
    "h015",
    "jainism",
    "Mahavira is traditionally identified as the:",
    [
      "First tirthankara",
      "Tenth tirthankara",
      "Twenty-fourth tirthankara",
      "Founder of the Buddhist sangha",
    ],
    2,
    "Mahavira is the 24th tirthankara in Jain tradition. Rishabhanatha is the first and Parshvanatha the 23rd.",
    "ancient",
    88,
  ),
  q(
    "h016",
    "jainism",
    "Which set describes the Jain three jewels?",
    [
      "Buddha, dhamma, sangha",
      "Ritual, conquest, taxation",
      "Faith, empire, sacrifice",
      "Right faith, right knowledge, right conduct",
    ],
    3,
    "The Jain three jewels are right faith, right knowledge and right conduct. Distinguishing them from the Buddhist three jewels is a common comparison task.",
    "ancient",
    89,
  ),
  q(
    "h017",
    "invasions-ancient",
    "Alexander’s battle with Porus is placed in which year?",
    ["326 BCE", "261 BCE", "78 CE", "320 CE"],
    0,
    "Alexander’s campaign and battle with Porus are placed in 326 BCE, before the establishment of Mauryan power.",
    "ancient",
    92,
  ),
  q(
    "h018",
    "mauryas",
    "Which sequence correctly orders these Mauryan rulers?",
    [
      "Ashoka → Bindusara → Chandragupta",
      "Chandragupta → Bindusara → Ashoka",
      "Bindusara → Ashoka → Chandragupta",
      "Chandragupta → Ashoka → Bindusara",
    ],
    1,
    "Chandragupta founded the dynasty, Bindusara succeeded him, and Ashoka followed Bindusara.",
    "ancient",
    94,
  ),
  q(
    "h019",
    "mauryas",
    "The Greek name Sandrocottus is associated with:",
    ["Samudragupta", "Kanishka", "Chandragupta Maurya", "Harsha"],
    2,
    "Greek accounts use names such as Sandrocottus for Chandragupta Maurya. Do not confuse him with Chandragupta I or II of the Gupta dynasty.",
    "ancient",
    95,
  ),
  q(
    "h020",
    "post-mauryas",
    "Who is associated with founding the Shunga dynasty?",
    ["Gautamiputra Satakarni", "Vasudeva Kanva", "Kanishka", "Pushyamitra"],
    3,
    "Pushyamitra Shunga established the Shunga dynasty after the last Mauryan ruler. Vasudeva belongs to the later Kanva succession.",
    "ancient",
    102,
  ),
  q(
    "h021",
    "kushanas",
    "Kanishka belonged to which dynasty?",
    ["Kushana", "Haryanka", "Chola", "Pala"],
    0,
    "Kanishka was a Kushana ruler associated with Buddhist patronage and political connections across northwestern India and Central Asia.",
    "ancient",
    117,
  ),
  q(
    "h022",
    "sangam",
    "Which trio names the major crowned kingdoms of early Tamil country?",
    [
      "Pala, Pratihara, Rashtrakuta",
      "Chera, Chola, Pandya",
      "Shunga, Kanva, Nanda",
      "Sayyid, Lodi, Khalji",
    ],
    1,
    "Chera, Chola and Pandya are the three major crowned kingdoms associated with the early Tamil/Sangam historical setting.",
    "ancient",
    118,
  ),
  q(
    "h023",
    "sangam",
    "Tolkappiyam is principally associated with:",
    [
      "Persian court history",
      "Mughal land revenue",
      "Tamil grammar",
      "British constitutional reform",
    ],
    2,
    "Tolkappiyam is an early work of Tamil grammar. It belongs in the Tamil literary tradition rather than the later Persian court tradition.",
    "ancient",
    121,
  ),
  q(
    "h024",
    "gupta",
    "Harisena’s Allahabad pillar inscription praises which Gupta ruler?",
    ["Chandragupta Maurya", "Kumaragupta", "Harsha", "Samudragupta"],
    3,
    "Harisena’s prashasti on the Allahabad pillar is a central source for Samudragupta’s achievements. As royal praise, it also needs critical reading.",
    "ancient",
    124,
  ),
  q(
    "h025",
    "gupta",
    "Fa-Hien’s visit is associated with the reign of:",
    ["Chandragupta II", "Chandragupta Maurya", "Akbar", "Rajaraja I"],
    0,
    "The notes associate Fa-Hien’s visit with Chandragupta II. Xuanzang is linked to the later age of Harsha.",
    "ancient",
    127,
  ),
  q(
    "h026",
    "harsha",
    "Which ruler checked Harsha’s expansion into the Deccan?",
    ["Bimbisara", "Pulakeshin II", "Ibrahim Lodi", "Sher Shah"],
    1,
    "Pulakeshin II of the Chalukyas checked Harsha’s southern expansion. The encounter belongs to the seventh-century regional political landscape.",
    "ancient",
    134,
  ),
  q(
    "h027",
    "tripartite",
    "The tripartite struggle for Kannauj involved:",
    [
      "Cholas, Cheras and Pandyas",
      "Mughals, Marathas and Sikhs",
      "Palas, Pratiharas and Rashtrakutas",
      "Nandas, Mauryas and Shungas",
    ],
    2,
    "Palas, Gurjara-Pratiharas and Rashtrakutas competed for influence over Kannauj. Their principal regional bases differed.",
    "sultanate",
    2,
  ),
  q(
    "h028",
    "tripartite",
    "Which dynasty patronised both Nalanda and Vikramashila?",
    ["Lodi", "Khalji", "Sur", "Pala"],
    3,
    "The Pala rulers were major patrons of Buddhist learning, including Nalanda and Vikramashila.",
    "sultanate",
    21,
  ),
  q(
    "h029",
    "cholas",
    "Which Chola ruler is associated with the title Gangaikonda Chola and a northern expedition?",
    ["Rajendra I", "Bahlul Lodi", "Dharmapala", "Iltutmish"],
    0,
    "Rajendra I’s northern expedition is associated with the Gangaikonda title. Distinguish him from his father Rajaraja I.",
    "sultanate",
    121,
  ),
  q(
    "h030",
    "turkish-conquests",
    "Who defeated Prithviraj Chauhan in the second battle of Tarain?",
    ["Mahmud of Ghazni", "Muhammad of Ghur", "Muhammad bin Qasim", "Babur"],
    1,
    "Muhammad of Ghur defeated Prithviraj in the second battle of Tarain in 1192. Mahmud of Ghazni belongs to an earlier series of campaigns.",
    "sultanate",
    37,
  ),
  q(
    "h031",
    "mamluks",
    "Who founded the Mamluk dynasty at Delhi?",
    ["Balban", "Alauddin Khalji", "Qutbuddin Aibak", "Ghiyasuddin Tughlaq"],
    2,
    "Qutbuddin Aibak founded Mamluk rule at Delhi in 1206. Iltutmish subsequently consolidated the state.",
    "sultanate",
    43,
  ),
  q(
    "h032",
    "mamluks",
    "Who completed the Qutb Minar according to the notes?",
    ["Babur", "Firoz Shah", "Sikandar Lodi", "Iltutmish"],
    3,
    "Aibak initiated construction and Iltutmish completed the main early structure. Later rulers carried out repairs and additions.",
    "sultanate",
    51,
  ),
  q(
    "h033",
    "khaljis",
    "Alauddin Khalji’s market regulations are most directly connected to which state need?",
    [
      "Maintaining a large standing army at controlled cost",
      "Financing European trading companies",
      "Establishing elected village councils",
      "Replacing cavalry with a navy",
    ],
    0,
    "Controlled prices helped support a large standing army. The regulations should be studied alongside military and revenue measures.",
    "sultanate",
    79,
    "application",
  ),
  q(
    "h034",
    "tughlaqs",
    "Token currency and the attempted capital transfer to Daulatabad are associated with:",
    ["Firoz Shah Tughlaq", "Muhammad bin Tughlaq", "Razia", "Sikandar Lodi"],
    1,
    "These experiments belong to Muhammad bin Tughlaq. Firoz Shah is better associated with canals and other administrative/public works measures.",
    "sultanate",
    86,
  ),
  q(
    "h035",
    "later-sultanate",
    "Which dynasty ruled Delhi immediately before Babur’s victory at Panipat?",
    ["Sayyid", "Tughlaq", "Lodi", "Khalji"],
    2,
    "Ibrahim Lodi was defeated by Babur in 1526, ending Lodi rule at Delhi and opening the Mughal period.",
    "sultanate",
    110,
  ),
  q(
    "h036",
    "vijayanagara",
    "Who founded the Vijayanagara kingdom?",
    [
      "Akbar and Bairam Khan",
      "Rajaraja and Rajendra",
      "Gopala and Dharmapala",
      "Harihara and Bukka",
    ],
    3,
    "Harihara and Bukka founded Vijayanagara in 1336. The early ruling line is known as the Sangama dynasty.",
    "sultanate",
    130,
  ),
  q(
    "h037",
    "vijayanagara",
    "Which interpretation of the battle of Talikota is most accurate?",
    [
      "It devastated the capital, but successor rulers continued the kingdom",
      "It founded the Sangama dynasty",
      "It ended every form of Vijayanagara rule immediately",
      "It was a battle against the East India Company",
    ],
    0,
    "The defeat in 1565 devastated Vijayanagara, but political rule continued under successors. Destruction of a capital is not identical to immediate extinction of a polity.",
    "sultanate",
    149,
    "application",
  ),
  q(
    "h038",
    "bahmani",
    "Mahmud Gawan is especially associated with which kingdom?",
    ["Pala", "Bahmani", "Nanda", "Lodi"],
    1,
    "Mahmud Gawan served the Bahmani kingdom and is associated with administrative reforms and a madrasa at Bidar.",
    "sultanate",
    158,
  ),
  q(
    "h039",
    "babur",
    "Which sequence of Babur’s battles is chronological?",
    [
      "Khanwa → Panipat → Ghaghra → Chanderi",
      "Ghaghra → Chanderi → Khanwa → Panipat",
      "Panipat → Khanwa → Chanderi → Ghaghra",
      "Chanderi → Panipat → Ghaghra → Khanwa",
    ],
    2,
    "The usual sequence is Panipat (1526), Khanwa (1527), Chanderi (1528), Ghaghra (1529).",
    "mughals",
    4,
    "application",
  ),
  q(
    "h040",
    "humayun",
    "Humayun’s defeat at Kannauj in 1540 was at the hands of:",
    ["Rana Sanga", "Hemu", "Ibrahim Lodi", "Sher Shah"],
    3,
    "Sher Shah defeated Humayun at Kannauj (also called Bilgram) in 1540, after the earlier defeat at Chausa.",
    "mughals",
    12,
  ),
  q(
    "h041",
    "akbar-expansion",
    "The second battle of Panipat in 1556 was fought between Akbar’s forces and:",
    ["Hemu", "Ibrahim Lodi", "Rana Sanga", "Ahmad Shah Abdali"],
    0,
    "Akbar’s forces, led by Bairam Khan, defeated Hemu. Ibrahim Lodi belongs to the first battle and Abdali to the third.",
    "mughals",
    27,
  ),
  q(
    "h042",
    "mughal-administration",
    "Which sequence runs from the largest to the smallest administrative unit?",
    [
      "Village → suba → sarkar → pargana",
      "Suba → sarkar → pargana → village",
      "Sarkar → village → suba → pargana",
      "Pargana → suba → village → sarkar",
    ],
    1,
    "A suba was a province, divided into sarkars, then parganas and villages.",
    "mughals",
    71,
    "application",
  ),
  q(
    "h043",
    "mansab-jagir",
    "In the mansabdari system, sawar primarily indicated:",
    [
      "A permanent land title",
      "The religious status of a noble",
      "The cavalry obligation attached to a rank",
      "The name of a province",
    ],
    2,
    "Sawar concerned the number of cavalrymen to be maintained; zat expressed personal rank/status. A jagir was a revenue assignment.",
    "mughals",
    85,
  ),
  q(
    "h044",
    "mansab-jagir",
    "Which statement best describes a Mughal jagir?",
    [
      "An independent sovereign kingdom",
      "An elected village council",
      "A religious debate hall",
      "An assignment of revenue",
    ],
    3,
    "A jagir assigned revenue to its holder, often in lieu of salary. It did not automatically convey private ownership or independent sovereignty over the land.",
    "mughals",
    92,
    "application",
  ),
  q(
    "h045",
    "akbar-culture",
    "Akbar’s Ibadat Khana was located at:",
    ["Fatehpur Sikri", "Patna", "Daulatabad", "Thanjavur"],
    0,
    "The Ibadat Khana was established at Fatehpur Sikri for religious discussion.",
    "mughals",
    98,
  ),
  q(
    "h046",
    "jahangir",
    "Sir Thomas Roe visited the court of:",
    ["Babur", "Jahangir", "Aurangzeb", "Sher Shah"],
    1,
    "Roe’s embassy visited Jahangir’s court in the early seventeenth century. This links Mughal court history with English trading ambitions.",
    "mughals",
    114,
  ),
  q(
    "h047",
    "aurangzeb",
    "Which emperor succeeded in the Mughal war of succession involving Dara Shikoh?",
    ["Akbar", "Jahangir", "Aurangzeb", "Humayun"],
    2,
    "Aurangzeb emerged victorious in the succession conflict involving Dara Shikoh and his other brothers.",
    "mughals",
    122,
  ),
  q(
    "h048",
    "europeans",
    "The English East India Company received its founding royal charter in:",
    ["1498", "1757", "1858", "1600"],
    3,
    "The English company was chartered in 1600. Its establishment as a trading company preceded territorial rule by well over a century.",
    "modern",
    6,
  ),
  q(
    "h049",
    "carnatic",
    "The battle of Wandiwash in 1760 was significant chiefly because it:",
    [
      "Weakened French military power in India",
      "Ended the Mughal dynasty",
      "Created the Indian National Congress",
      "Established the Permanent Settlement",
    ],
    0,
    "The English victory at Wandiwash weakened French military prospects during the third Carnatic war.",
    "modern",
    16,
  ),
  q(
    "h050",
    "bengal",
    "Which battle took place in 1764?",
    ["Plassey", "Buxar", "First Panipat", "Talikota"],
    1,
    "Buxar was fought in 1764. Plassey was in 1757; the Company’s diwani grant followed in 1765.",
    "modern",
    19,
  ),
  q(
    "h051",
    "bengal",
    "The Company’s diwani rights concerned primarily:",
    [
      "Royal succession",
      "Naval command",
      "Revenue collection",
      "Religious appointments",
    ],
    2,
    "Diwani rights concerned revenue collection. The 1765 grant was a key step in the Company’s territorial and fiscal power.",
    "modern",
    20,
  ),
  q(
    "h052",
    "mysore-marathas",
    "The third battle of Panipat in 1761 was fought between the Marathas and:",
    ["Babur", "Robert Clive", "Hemu", "Ahmad Shah Abdali"],
    3,
    "The Marathas fought Ahmad Shah Abdali (Durrani). This is distinct from the first and second battles of Panipat.",
    "mains-1",
    6,
  ),
  q(
    "h053",
    "annexation",
    "Which pairing is correct?",
    [
      "Wellesley — subsidiary alliance",
      "Dalhousie — founding the Arya Samaj",
      "Ripon — doctrine of lapse",
      "Curzon — Permanent Settlement",
    ],
    0,
    "Wellesley expanded the use of subsidiary alliances. The doctrine of lapse is associated with Dalhousie and Permanent Settlement with Cornwallis.",
    "modern",
    72,
  ),
  q(
    "h054",
    "company-acts",
    "Which act introduced a Board of Control over Company affairs?",
    [
      "Regulating Act 1773",
      "Pitt’s India Act 1784",
      "Charter Act 1813",
      "Indian Councils Act 1909",
    ],
    1,
    "Pitt’s India Act established the Board of Control, creating a system of supervision alongside the Company’s Court of Directors.",
    "mains-1",
    61,
  ),
  q(
    "h055",
    "revenue-colonial",
    "A revenue settlement made directly with individual cultivators is most closely associated with:",
    ["Permanent Settlement", "Mahalwari", "Ryotwari", "Mansabdari"],
    2,
    "Ryotwari involved settlement directly with cultivators. Permanent Settlement used zamindars, while Mahalwari assessed village or estate units.",
    "modern",
    12,
  ),
  q(
    "h056",
    "revenue-colonial",
    "The Permanent Settlement of Bengal was introduced under:",
    ["Wellesley", "Bentinck", "Dalhousie", "Cornwallis"],
    3,
    "Cornwallis introduced the Permanent Settlement in 1793. Its defining feature was a permanently fixed revenue demand on zamindars.",
    "modern",
    11,
  ),
  q(
    "h057",
    "governors",
    "Who became the first Viceroy of India after the transfer to Crown rule?",
    ["Canning", "Curzon", "Ripon", "Wavell"],
    0,
    "Canning was Governor-General during the revolt and became the first viceroy under Crown rule.",
    "mains-1",
    74,
  ),
  q(
    "h058",
    "revolt-1857",
    "Which development followed the revolt of 1857?",
    [
      "Creation of the East India Company",
      "Transfer of government from Company to Crown",
      "Introduction of the doctrine of lapse",
      "Foundation of the Mughal dynasty",
    ],
    1,
    "The Government of India Act 1858 transferred rule to the Crown. It ended the Company’s governing role.",
    "modern",
    69,
  ),
  q(
    "h059",
    "revolt-1857",
    "Nana Saheb is principally associated with which centre of the revolt?",
    ["Meerut", "Lucknow", "Kanpur", "Bareilly"],
    2,
    "Nana Saheb led the revolt at Kanpur. Link leaders to centres rather than memorising their names in isolation.",
    "mains-1",
    94,
  ),
  q(
    "h060",
    "reform-bengal",
    "Rammohun Roy is most closely associated with:",
    ["Arya Samaj", "Ghadar Party", "Home Rule League", "Brahmo Samaj"],
    3,
    "Rammohun Roy’s Brahmo tradition was central to nineteenth-century reform in Bengal. Arya Samaj belongs to Dayanand Saraswati.",
    "mains-1",
    115,
  ),
  q(
    "h061",
    "reform-west",
    "Who founded the Arya Samaj?",
    ["Dayanand Saraswati", "Vivekananda", "Jyotiba Phule", "Henry Derozio"],
    0,
    "Dayanand Saraswati founded Arya Samaj in 1875. Vivekananda is associated with Ramakrishna Mission and Phule with Satyashodhak Samaj.",
    "mains-1",
    140,
  ),
  q(
    "h062",
    "reform-west",
    "Satyashodhak Samaj is associated with:",
    [
      "Debendranath Tagore",
      "Jyotiba Phule",
      "Annie Besant",
      "Sir Syed Ahmad Khan",
    ],
    1,
    "Phule established Satyashodhak Samaj to challenge caste oppression and promote social reform.",
    "mains-1",
    133,
  ),
  q(
    "h063",
    "early-associations",
    "The Indian Association of Calcutta was founded in 1876 by Surendranath Banerjea and:",
    [
      "W. C. Bonnerjee",
      "Gopal Krishna Gokhale",
      "Anand Mohan Bose",
      "Mahatma Gandhi",
    ],
    2,
    "Surendranath Banerjea and Anand Mohan Bose founded the Indian Association in 1876, before the Congress.",
    "modern",
    90,
  ),
  q(
    "h064",
    "congress",
    "Who presided over the first session of the Indian National Congress?",
    [
      "Dadabhai Naoroji",
      "A. O. Hume",
      "Bal Gangadhar Tilak",
      "W. C. Bonnerjee",
    ],
    3,
    "W. C. Bonnerjee presided over the first Congress session in 1885. Do not confuse the organiser A. O. Hume with the first president.",
    "modern",
    93,
  ),
  q(
    "h065",
    "swadeshi",
    "The Swadeshi movement of 1905 developed directly in opposition to:",
    [
      "The partition of Bengal",
      "The Rowlatt Act",
      "The Simon Commission",
      "The Cripps proposals",
    ],
    0,
    "The Bengal partition of 1905 triggered the Swadeshi and boycott movement. The other events belong to later phases.",
    "freedom",
    8,
  ),
  q(
    "h066",
    "swadeshi",
    "Which action best illustrates the constructive side of Swadeshi?",
    [
      "Joining the Simon Commission",
      "Promoting indigenous industry and national education",
      "Supporting colonial imports exclusively",
      "Suspending all political activity",
    ],
    1,
    "Swadeshi included building indigenous enterprises and educational institutions alongside the boycott of foreign goods.",
    "freedom",
    15,
    "application",
  ),
  q(
    "h067",
    "league-revolutionaries",
    "The Komagata Maru incident occurred in:",
    ["1857", "1905", "1914", "1942"],
    2,
    "The Komagata Maru incident occurred in 1914. Study it with overseas Indian political activity and racial immigration restrictions.",
    "modern",
    108,
  ),
  q(
    "h068",
    "home-rule",
    "The Lucknow Pact between Congress and the Muslim League belongs to:",
    ["1906", "1909", "1929", "1916"],
    3,
    "The Lucknow Pact was concluded in 1916. It belongs to the period of Home Rule agitation and Congress reunification.",
    "modern",
    111,
  ),
  q(
    "h069",
    "constitutional-reforms",
    "Dyarchy in the provinces was introduced by the:",
    [
      "Government of India Act 1919",
      "Indian Councils Act 1909",
      "Charter Act 1833",
      "Government of India Act 1858",
    ],
    0,
    "The 1919 Act introduced provincial dyarchy, dividing subjects into transferred and reserved categories.",
    "mains-2",
    78,
  ),
  q(
    "h070",
    "constitutional-reforms",
    "Which reform is associated with the Indian Councils Act 1909?",
    [
      "Complete independence",
      "Separate electorates for Muslims",
      "Universal adult franchise",
      "A sovereign constituent assembly",
    ],
    1,
    "The 1909 reforms introduced separate electorates for Muslims. They did not introduce universal adult franchise or responsible national government.",
    "modern",
    105,
  ),
  q(
    "h071",
    "gandhi-early",
    "The Ahmedabad struggle of 1918 concerned:",
    [
      "Indigo planters",
      "Salt laws",
      "Mill workers",
      "Princely-state accession",
    ],
    2,
    "Ahmedabad involved mill workers and a wage dispute. Champaran concerned indigo cultivators, while Kheda concerned land revenue.",
    "modern",
    117,
  ),
  q(
    "h072",
    "gandhi-early",
    "The Jallianwala Bagh massacre occurred in:",
    ["1905", "1917", "1922", "1919"],
    3,
    "The massacre occurred at Amritsar in April 1919, during the period of agitation against the Rowlatt Act.",
    "modern",
    118,
  ),
  q(
    "h073",
    "non-cooperation",
    "Which event prompted Gandhi to suspend Non-Cooperation in 1922?",
    [
      "Chauri Chaura",
      "The Dandi March",
      "The Cabinet Mission",
      "The Surat split",
    ],
    0,
    "Violence at Chauri Chaura in February 1922 led Gandhi to suspend the movement. Dandi belongs to Civil Disobedience in 1930.",
    "freedom",
    43,
  ),
  q(
    "h074",
    "swarajists",
    "Which pair is associated with the Swarajist strategy of entering legislative councils?",
    [
      "Tilak and Lajpat Rai",
      "C. R. Das and Motilal Nehru",
      "Gandhi and Vinoba Bhave",
      "Bose and Mohan Singh",
    ],
    1,
    "C. R. Das and Motilal Nehru advocated council entry to challenge colonial government from within legislatures.",
    "modern",
    128,
  ),
  q(
    "h075",
    "bardoli",
    "The Bardoli Satyagraha of 1928 was led by:",
    ["Jawaharlal Nehru", "C. R. Das", "Vallabhbhai Patel", "B. R. Ambedkar"],
    2,
    "Patel led the Bardoli movement against an increased land revenue assessment.",
    "mains-2",
    114,
  ),
  q(
    "h076",
    "civil-disobedience",
    "The Dandi March was directed immediately against:",
    [
      "The doctrine of lapse",
      "The partition of Bengal",
      "The Vernacular Press Act",
      "The salt law",
    ],
    3,
    "Gandhi’s 1930 march culminated in breaking the salt law. Salt connected an everyday necessity with a mass political campaign.",
    "freedom",
    63,
  ),
  q(
    "h077",
    "civil-disobedience",
    "Which sequence is correct?",
    [
      "Lahore Purna Swaraj resolution → Dandi March → Gandhi–Irwin Pact",
      "Dandi March → Lahore resolution → Gandhi–Irwin Pact",
      "Gandhi–Irwin Pact → Dandi March → Lahore resolution",
      "Lahore resolution → Gandhi–Irwin Pact → Dandi March",
    ],
    0,
    "The Lahore resolution was in December 1929, the Dandi March in 1930 and the Gandhi–Irwin Pact in 1931.",
    "freedom",
    58,
    "application",
  ),
  q(
    "h078",
    "poona-pact",
    "The Poona Pact provided for the Depressed Classes through:",
    [
      "Separate sovereign territories",
      "Reserved seats within a joint electorate",
      "Abolition of all electoral representation",
      "A hereditary council",
    ],
    1,
    "The pact used reserved seats in joint electorates, replacing the separate-electorate arrangement proposed in the Communal Award.",
    "mains-2",
    128,
  ),
  q(
    "h079",
    "war-quit-india",
    "Which proposal immediately preceded the Quit India movement in 1942?",
    [
      "Cabinet Mission",
      "Mountbatten Plan",
      "Cripps Mission",
      "Morley–Minto reforms",
    ],
    2,
    "The failure of the Cripps Mission in 1942 preceded Quit India. Cabinet Mission and Mountbatten Plan belong to 1946 and 1947.",
    "modern",
    154,
  ),
  q(
    "h080",
    "war-quit-india",
    "The underground Congress Radio during Quit India is associated with:",
    ["Sarojini Naidu", "Annie Besant", "Madam Cama", "Usha Mehta"],
    3,
    "Usha Mehta was associated with underground Congress Radio during the Quit India movement.",
    "modern",
    159,
  ),
  q(
    "h081",
    "ina",
    "The INA trials of Sehgal, Shah Nawaz and Dhillon took place at:",
    ["The Red Fort", "Aga Khan Palace", "Cellular Jail", "Sabarmati Ashram"],
    0,
    "The three officers were tried at the Red Fort. The trials became a focus of widespread public mobilisation.",
    "modern",
    168,
  ),
  q(
    "h082",
    "partition-negotiations",
    "The Cabinet Mission came to India in:",
    ["1942", "1946", "1935", "1947"],
    1,
    "The Cabinet Mission arrived in 1946 with proposals for a constitutional settlement. It must be distinguished from the Mountbatten Plan of 1947.",
    "modern",
    169,
  ),
  q(
    "h083",
    "women-students",
    "Which is a sound approach to assessing women’s role in the freedom struggle?",
    [
      "Mention one leader and assume all regions were identical",
      "Ignore participation outside formal office",
      "Compare leadership and everyday participation across several movements",
      "Assume political participation removed every social inequality",
    ],
    2,
    "A strong answer compares leadership, picketing, organisation and underground work across movements, while assessing social limits and regional differences.",
    "freedom",
    92,
    "application",
  ),
  q(
    "h084",
    "partition-rehab",
    "Which combination captures major immediate challenges of partition?",
    [
      "Only a change of flags",
      "Only the end of Company trade",
      "Only the construction of a new capital",
      "Displacement, rehabilitation and division of institutions and assets",
    ],
    3,
    "Partition combined humanitarian displacement with administrative and economic division. An answer should connect these dimensions.",
    "republic",
    3,
    "application",
  ),
  q(
    "h085",
    "integration",
    "Who worked closely with Vallabhbhai Patel on princely-state integration?",
    ["V. P. Menon", "Lord Curzon", "W. C. Bonnerjee", "Dupleix"],
    0,
    "V. P. Menon worked closely with Patel in the integration process. Use the individual state cases to understand their negotiations.",
    "republic",
    27,
  ),
  q(
    "h086",
    "integration",
    "Operation Polo in 1948 concerned:",
    ["Goa", "Hyderabad", "Sikkim", "Travancore"],
    1,
    "Operation Polo was the September 1948 military action in Hyderabad. Goa’s incorporation followed a different operation in 1961.",
    "republic",
    36,
  ),
  q(
    "h087",
    "states-reorganisation",
    "Which sequence correctly names the states formed in 1953 and 1956?",
    [
      "Andhra Pradesh in 1953; Andhra State in 1956",
      "Both were formed in 1947",
      "Andhra State in 1953; Andhra Pradesh in 1956",
      "Telangana in 1953; Andhra State in 1956",
    ],
    2,
    "Andhra State was created in 1953. Andhra Pradesh was formed in 1956 through reorganisation. A correction note accompanies the original slide’s imprecise name.",
    "republic",
    21,
  ),
  q(
    "h088",
    "states-reorganisation",
    "The JVP Committee took its name from Jawaharlal Nehru, Vallabhbhai Patel and:",
    ["V. P. Menon", "Vinoba Bhave", "V. V. Giri", "Pattabhi Sitaramayya"],
    3,
    "JVP refers to Jawaharlal Nehru, Vallabhbhai Patel and Pattabhi Sitaramayya. It examined demands for linguistic reorganisation.",
    "republic",
    20,
  ),
  q(
    "h089",
    "kashmir",
    "Who was the ruler of Jammu and Kashmir at the time of accession in 1947?",
    ["Hari Singh", "Hamidullah Khan", "Mir Osman Ali Khan", "Hanwant Singh"],
    0,
    "Hari Singh was the ruler of Jammu and Kashmir. The other names belong to Bhopal, Hyderabad and Jodhpur respectively.",
    "republic",
    42,
  ),
];

// Include adjacent slides when a statement depends on its heading or continuation.
const rangeCorrections = {
  h022: [118, 119],
  h025: [126, 127],
  h027: [1, 3],
  h033: [78, 81],
  h034: [86, 88],
  h035: [110, 111],
  h039: [4, 8],
  h042: [71, 78],
  h054: [60, 61],
  h062: [131, 133],
  h066: [13, 15],
  h069: [77, 78],
  h077: [58, 66],
  h078: [128, 130],
  h084: [2, 4],
};
for (const question of questions) {
  const range = rangeCorrections[question.id];
  if (range)
    Object.assign(question.sources[0], { from: range[0], to: range[1] });
}

// Additional authority where a source slide is incomplete or contains an error.
questions.find((q) => q.id === "h078").evidence = [
  {
    title: "Ministry of External Affairs · archival documents, Volume 10",
    url: "https://www.mea.gov.in/Images/CPV/Volume10.pdf",
  },
];
questions.find((q) => q.id === "h087").evidence = [
  {
    title: "Andhra State Act, 1953",
    url: "https://www.indiacode.nic.in/bitstream/123456789/2176/1/195330.pdf",
  },
  {
    title: "Andhra Pradesh PSC · History",
    url: "https://portal-psc.ap.gov.in/HomePages/History",
  },
];
