import type { DictKanji, DictWords } from './dictionary-types';

// ============================================
// Fetch-once-and-cache singletons for the dictionary data generated by
// tools/nihongo-dict/build.mjs. Served as static assets under
// public/data/nihongo/ (NOT bundled into the JS chunk) so /nihongo's
// other tabs stay fast — only opening the Dictionary tab pays for this.
// jmdict.json is ~8.5MB gzipped; the browser's HTTP cache makes every
// load after the first free.
// ============================================

let wordsPromise: Promise<DictWords> | null = null;
let kanjiPromise: Promise<DictKanji> | null = null;

export function loadDictionary(): Promise<DictWords> {
  if (!wordsPromise) {
    wordsPromise = fetch('/data/nihongo/jmdict.json').then((res) => {
      if (!res.ok) throw new Error(`Failed to load dictionary (${res.status})`);
      return res.json();
    });
  }
  return wordsPromise;
}

export function loadKanjiDic(): Promise<DictKanji> {
  if (!kanjiPromise) {
    kanjiPromise = fetch('/data/nihongo/kanjidic2.json').then((res) => {
      if (!res.ok) throw new Error(`Failed to load kanji dictionary (${res.status})`);
      return res.json();
    });
  }
  return kanjiPromise;
}
