// ============================================
// Types for the offline JMdict/KANJIDIC2 dictionary data generated by
// tools/nihongo-dict/build.mjs into public/data/nihongo/*.json. Mirrors
// the pipeline's compact output shape, not the raw jmdict-simplified
// schema (see build.mjs for the transform).
// ============================================

export interface DictSense {
  /** JMdict tag codes (part of speech + misc/field/dialect), e.g. "n", "v5k", "uk". Look up in DictWords.posTags for a human-readable label. */
  tags: string[];
  gloss: string[];
}

export interface DictWordEntry {
  id: string;
  kanji: string[];
  kana: string[];
  /** True if any kanji/kana form is a "common" word per JMdict. */
  common: boolean;
  senses: DictSense[];
}

export interface DictWords {
  version: string;
  dictDate: string;
  /** Tag code -> human-readable label, e.g. { n: "noun (common) (futsuumeishi)" }. */
  posTags: Record<string, string>;
  words: DictWordEntry[];
}

export interface DictKanjiEntry {
  literal: string;
  meanings: string[];
  onReadings: string[];
  kunReadings: string[];
  strokeCount: number | null;
  jlpt: number | null;
  grade: number | null;
  frequency: number | null;
}

export interface DictKanji {
  version: string;
  dictDate: string;
  kanji: DictKanjiEntry[];
}
