"""Check the Group B library, key comparison, recovered figures and marking."""
import base64
import json
import os
import socket
import struct
import sys
import time
import urllib.request

pages = json.load(urllib.request.urlopen('http://127.0.0.1:9222/json', timeout=10))
page = next(p for p in pages if p.get('type') == 'page' and '/udc-ldc' in p.get('url', ''))
path = page['webSocketDebuggerUrl'].split('127.0.0.1:9222', 1)[1]
s = socket.create_connection(('127.0.0.1', 9222), timeout=15)
key = base64.b64encode(os.urandom(16)).decode()
s.sendall((f'GET {path} HTTP/1.1\r\nHost: 127.0.0.1:9222\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Key: {key}\r\nSec-WebSocket-Version: 13\r\nOrigin: http://127.0.0.1:9222\r\n\r\n').encode())
head = b''
while b'\r\n\r\n' not in head:
    head += s.recv(4096)
assert b' 101 ' in head, head[:250]
serial = 0
exceptions = []

def exact(n):
    data = b''
    while len(data) < n:
        data += s.recv(n - len(data))
    return data

def command(method, params=None):
    global serial
    serial += 1
    data = json.dumps({'id': serial, 'method': method, 'params': params or {}}).encode()
    mask = os.urandom(4)
    n = len(data)
    hdr = bytes([0x81, 0x80 | n]) if n < 126 else bytes([0x81, 0x80 | 126]) + struct.pack('!H', n)
    s.sendall(hdr + mask + bytes(byte ^ mask[i % 4] for i, byte in enumerate(data)))
    while True:
        h = exact(2)
        length = h[1] & 127
        if length == 126:
            length = struct.unpack('!H', exact(2))[0]
        elif length == 127:
            length = struct.unpack('!Q', exact(8))[0]
        message = json.loads(exact(length))
        if message.get('method') == 'Runtime.exceptionThrown':
            exceptions.append(message)
        if message.get('id') == serial:
            assert 'error' not in message, message
            return message.get('result', {})

def evaluate(js):
    result = command('Runtime.evaluate', {'expression': js, 'returnByValue': True, 'awaitPromise': True})
    assert 'exceptionDetails' not in result, result
    return result['result'].get('value')

def wait_for(js):
    for _ in range(100):
        if evaluate(js):
            return
        time.sleep(.2)
    raise AssertionError(js)

def click_tab(name):
    evaluate(f"[...document.querySelectorAll('.udc-tabs button')].find(b=>b.textContent.trim()==={json.dumps(name)}).click()")
    time.sleep(.2)

def browse(exam, subject):
    click_tab('Group B papers')
    evaluate(f"[...document.querySelectorAll('.udc-library-sitting')].find(a=>a.querySelector('h3').textContent.includes({json.dumps(exam)})).querySelectorAll('.udc-library-paper').forEach(p=>{{if(p.querySelector('strong').textContent.includes({json.dumps(subject)}))p.querySelector('button')?.click()}})")
    wait_for("!!document.querySelector('.udc-question-card')")

command('Runtime.enable')
command('Page.enable')
if len(sys.argv) > 1:
    command('Page.navigate', {'url': sys.argv[1]})
    wait_for("document.querySelector('.udc-hero h1')?.textContent.includes('Group B')")
command('Emulation.setDeviceMetricsOverride', {'width': 390, 'height': 900, 'deviceScaleFactor': 1, 'mobile': True})
evaluate('location.reload()')
wait_for("document.querySelector('.udc-hero h1')?.textContent.includes('Group B')")
wait_for("document.querySelectorAll('.udc-tabs button').length === 5")
click_tab('Group B papers')
assert evaluate("document.querySelectorAll('.udc-library-paper').length") == 257
assert evaluate("document.body.scrollWidth <= innerWidth")
assert evaluate("document.querySelector('.udc-ldc-page').scrollHeight > document.querySelector('.udc-ldc-page').clientHeight")
assert evaluate("[...document.querySelectorAll('.udc-library-paper')].some(p=>p.innerText.includes('held unscored'))")
browse('Junior Accounts Officer (JAO)', 'Arithmetic')
assert evaluate("document.querySelectorAll('.udc-question-card').length") == 100
evaluate("document.querySelector('.udc-question-card .udc-option-label').closest('button').click()")
wait_for("document.querySelector('.udc-answer-sources')?.innerText.includes('Answers agree')")
assert evaluate("document.querySelector('.udc-answer-sources').innerText.includes('MPSC final key')")
assert evaluate("(async()=>{let a=document.querySelector('.udc-answer-sources a');return (await fetch(a.href)).status})()") == 200
browse('District Organiser / Junior Accounts Officer', 'General Knowledge & Reasoning')
assert evaluate("document.querySelectorAll('.udc-question-card').length === 100")
assert evaluate("document.querySelectorAll('.udc-question-card')[0].innerText.includes('mica mines child-labour-free')")
assert evaluate("document.querySelectorAll('.udc-question-card')[22].innerText.includes('Question Hour')")
assert evaluate("document.querySelectorAll('.udc-question-card')[24].innerText.includes('1 April 1935')")
assert evaluate("document.querySelectorAll('.udc-question-card')[32].innerText.includes('Agenda 21')")
assert evaluate("Array.from(document.querySelectorAll('.udc-question-card')).some(card=>card.innerText.includes('Nagar Van Yojana'))")
assert evaluate("Array.from(document.querySelectorAll('.udc-question-card')).some(card=>card.innerText.includes('Gekko mizoramensis'))")
assert evaluate("Array.from(document.querySelectorAll('.udc-question-card')).some(card=>card.innerText.includes('Anthology'))")
evaluate("document.querySelectorAll('.udc-question-card')[2].querySelectorAll('.udc-option-label')[3].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[2].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[2].innerText.includes('Ministry of Statistics and Programme Implementation initiative')")
evaluate("document.querySelectorAll('.udc-question-card')[30].querySelectorAll('.udc-option-label')[0].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[30].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[30].innerText.includes('largest protected area')")
browse('Group B (non-gazetted)', 'Arithmetic')
assert evaluate("document.querySelectorAll('.udc-question-card').length") == 100
# The mixed Computer/Arithmetic/Reasoning paper must split into its three
# reading modes: 30 quantitative stems, 35 reasoning, 35 computer (plain).
assert evaluate("document.querySelectorAll('.udc-question-card .udc-math-stem').length") == 30
assert evaluate("document.querySelectorAll('.udc-question-card .udc-reasoning-stem').length") == 35
assert evaluate("document.querySelectorAll('.udc-question-card .udc-math-option').length") == 120
assert evaluate("document.querySelectorAll('.udc-question-card img').length") == 6
evaluate("document.querySelectorAll('.udc-question-card')[74].scrollIntoView({block:'start'})")
wait_for("document.querySelectorAll('.udc-question-card')[74].querySelector('img').complete")
assert evaluate("document.querySelectorAll('.udc-question-card')[74].querySelector('img').naturalWidth > 500")
assert evaluate("document.querySelectorAll('.udc-question-card')[83].innerText.includes('investments')")
assert evaluate("(async()=>{let a=document.querySelectorAll('.udc-question-card')[83].querySelector('a');return (await fetch(a.href)).status})()") == 200
evaluate("document.querySelectorAll('.udc-question-card')[74].querySelector('.udc-option-label').closest('button').click()")
wait_for("document.querySelectorAll('.udc-question-card')[74].innerText.includes('Answers agree')")
with open('/tmp/group-b-mobile-check.png', 'wb') as image:
    image.write(base64.b64decode(command('Page.captureScreenshot', {'format': 'png'})['data']))
evaluate("[...document.querySelectorAll('button')].find(b=>b.textContent.includes('Filters')).click()")
wait_for("[...document.querySelectorAll('button')].some(b=>b.textContent.includes('Answers differ'))")
evaluate("[...document.querySelectorAll('button')].find(b=>b.textContent.includes('Clear paper selection')).click()")
evaluate("[...document.querySelectorAll('button')].find(b=>b.textContent.includes('Answers differ')).click()")
assert evaluate("document.querySelectorAll('.udc-question-card').length > 0")
click_tab('exam')
evaluate("[...document.querySelectorAll('button')].find(b=>b.textContent.includes('Sub-Inspector of Statistics')&&b.textContent.includes('Paper II')).click()")
wait_for("document.body.innerText.includes('0/100 answered')")
evaluate("[...document.querySelectorAll('button')].find(b=>b.textContent.trim()==='Submit').click()")
assert evaluate("document.body.innerText.includes('0 / 100')")
assert evaluate("document.body.innerText.includes('Arithmetic')&&document.body.innerText.includes('General Knowledge')")
command('Emulation.setDeviceMetricsOverride', {'width': 1280, 'height': 900, 'deviceScaleFactor': 1, 'mobile': False})
click_tab('Group B papers')
assert evaluate("document.body.scrollWidth <= innerWidth")
assert evaluate("document.querySelector('.udc-library-progress').innerText.includes('3,611 ready to practise')")
assert evaluate("document.querySelector('.udc-library-progress').innerText.includes('1,618 with official answers')")
browse('Junior Engineer, PHE & PWD', 'General English')
assert evaluate("document.querySelectorAll('.udc-question-card').length === 81")
assert evaluate("document.querySelectorAll('.udc-question-card')[0].innerText.includes('present disturbance will soon')")
assert evaluate("Array.from(document.querySelectorAll('.udc-question-card')).some(card=>card.innerText.includes('omniscient')&&card.innerText.includes('omnipresent'))")
assert evaluate("Array.from(document.querySelectorAll('.udc-question-card')).some(card=>card.innerText.includes('in case of emergencies')&&card.innerText.includes('not scored'))")
assert evaluate("Array.from(document.querySelectorAll('.udc-question-card')).some(card=>card.innerText.includes('Write an essay on any one')&&card.innerText.includes('Talent versus Hard Work'))")
browse('AAO / AAAO / Field Facilitator', 'General English')
assert evaluate("document.querySelectorAll('.udc-question-card').length === 64")
assert evaluate("document.querySelectorAll('.udc-question-card')[0].innerText.includes('brilliant')")
assert evaluate("Array.from(document.querySelectorAll('.udc-question-card')).some(card=>card.innerText.includes('Write a précis')&&card.innerText.includes('Gardening is one of the oldest'))")
assert evaluate("Array.from(document.querySelectorAll('.udc-question-card')).some(card=>card.innerText.includes('Write an essay on any one')&&card.innerText.includes('Rainwater Harvesting'))")
browse('District Organiser / Junior Accounts Officer', 'General English')
assert evaluate("document.querySelectorAll('.udc-question-card').length === 63")
assert evaluate("document.querySelectorAll('.udc-question-card')[0].innerText.includes('pronounced the word')")
assert evaluate("Array.from(document.querySelectorAll('.udc-question-card')).some(card=>card.innerText.includes('12 a.m.–3 a.m.'))")
assert evaluate("document.querySelectorAll('.udc-question-card')[35].innerText.includes('not scored')")
assert evaluate("Array.from(document.querySelectorAll('.udc-question-card')).some(card=>card.innerText.includes('write a précis')&&card.innerText.includes('bad habits'))")
assert evaluate("Array.from(document.querySelectorAll('.udc-question-card')).some(card=>card.innerText.includes('man-made reservoir')&&card.innerText.includes('speedometer'))")
browse('District Organiser / Junior Accounts Officer', 'General Knowledge & Reasoning')
assert evaluate("document.querySelectorAll('.udc-question-card').length === 100")
assert evaluate("document.querySelectorAll('.udc-question-card')[50].innerText.includes('√(√100 + √36)')")
assert evaluate("document.querySelectorAll('.udc-question-card')[51].innerText.includes('15% of 600')")
assert evaluate("document.querySelectorAll('.udc-question-card')[82].innerText.includes('not scored')")
for index in (64, 79, 85, 88, 93, 94, 95):
    evaluate(f"document.querySelectorAll('.udc-question-card')[{index}].scrollIntoView({{block:'center'}})")
    # Lazy figure loads are sometimes aborted mid-session (complete=true,
    # naturalWidth 0) when React re-renders during paper switching; relaunch
    # the load on each poll until it settles, as the ASI figure loop below does.
    wait_for(f"(()=>{{const im=document.querySelectorAll('.udc-question-card')[{index}].querySelector('img');if(im&&!im.naturalWidth&&im.complete){{im.loading='eager';im.src=im.currentSrc||im.src;}}return !!im&&im.naturalWidth>0}})()")
evaluate("document.querySelectorAll('.udc-question-card')[71].querySelectorAll('.udc-option-label')[0].closest('button').click()")
wait_for("document.querySelectorAll('.udc-question-card')[71].innerText.includes('Only option A is a root')")
evaluate("document.querySelectorAll('.udc-question-card')[92].querySelectorAll('.udc-option-label')[0].closest('button').click()")
wait_for("document.querySelectorAll('.udc-question-card')[92].innerText.includes('In both, S occupies the middle position')")
browse('Group B technical common exam, Health & Family Welfare', 'General Studies')
assert evaluate("document.querySelectorAll('.udc-question-card').length === 100")
assert evaluate("document.querySelectorAll('.udc-question-card')[94].innerText.includes('not correctly matched')")
evaluate("document.querySelectorAll('.udc-question-card')[80].querySelectorAll('.udc-option-label')[1].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[80].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[80].innerText.includes('26 July 2021')")
evaluate("document.querySelectorAll('.udc-question-card')[94].querySelectorAll('.udc-option-label')[2].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[94].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[94].innerText.includes('The established folktale is') && document.querySelectorAll('.udc-question-card')[94].innerText.includes('Mizoram University')")
browse('Group B technical common exam, Health & Family Welfare', 'General English')
assert evaluate("document.querySelectorAll('.udc-question-card').length === 55")
evaluate("document.querySelectorAll('.udc-question-card')[0].querySelectorAll('.udc-option-label')[2].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[0].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[0].innerText.includes('preposition')")
assert evaluate("document.querySelectorAll('.udc-question-card')[21].innerText.includes('not scored') && document.querySelectorAll('.udc-question-card')[21].innerText.includes('No offered option fixes the malformed sentence')")
evaluate("document.querySelectorAll('.udc-question-card')[50].querySelector('button').click()")
assert evaluate("document.querySelectorAll('.udc-question-card')[50].innerText.includes('Sample title')")
browse('Sub-Inspector FCS&CA / Receptionist H&FW', 'General Knowledge, Arithmetic & Reasoning')
assert evaluate("document.querySelectorAll('.udc-question-card').length === 100")
assert evaluate("document.querySelectorAll('.udc-question-card')[0].innerText.includes('Mizoram Liquor') && document.querySelectorAll('.udc-question-card')[7].innerText.includes('Red Fort')")
evaluate("document.querySelectorAll('.udc-question-card')[0].querySelectorAll('.udc-option-label')[3].closest('button').click()")
wait_for("document.querySelectorAll('.udc-question-card')[0].innerText.includes('Kiwi is not named')")
assert evaluate("document.querySelectorAll('.udc-question-card')[23].innerText.includes('Articles 25-28')")
evaluate("document.querySelectorAll('.udc-question-card')[33].querySelectorAll('.udc-option-label')[3].closest('button').click()")
wait_for("document.querySelectorAll('.udc-question-card')[33].innerText.includes('Sailulak and Sairep')")
assert evaluate("document.querySelectorAll('.udc-question-card')[37].innerText.includes('Violet and blue light get scattered')")
assert evaluate("document.querySelectorAll('.udc-question-card')[29].innerText.includes('source checked · not scored')")
assert evaluate("document.querySelectorAll('.udc-question-card')[99].innerText.includes('source checked · not scored')")
evaluate("document.querySelectorAll('.udc-question-card')[83].querySelectorAll('.udc-option-label')[0].closest('button').click()")
wait_for("document.querySelectorAll('.udc-question-card')[83].innerText.includes('opposite 6 is 3')")
evaluate("document.querySelectorAll('.udc-question-card')[84].querySelectorAll('.udc-option-label')[0].closest('button').click()")
wait_for("document.querySelectorAll('.udc-question-card')[84].innerText.includes('first to the third letter')")
evaluate("document.querySelectorAll('.udc-question-card')[92].querySelectorAll('.udc-option-label')[1].closest('button').click()")
wait_for("document.querySelectorAll('.udc-question-card')[92].innerText.includes('B–E–G–A–C–F–D')")
assert evaluate("document.querySelectorAll('.udc-question-card')[96].querySelector('img')?.getAttribute('src').includes('q097.png') && document.querySelectorAll('.udc-question-card')[99].querySelector('img')?.getAttribute('src').includes('q100.png')")
evaluate("document.querySelectorAll('.udc-question-card')[97].querySelectorAll('.udc-option-label')[3].closest('button').click()")
wait_for("document.querySelectorAll('.udc-question-card')[97].innerText.includes('Option 4 supplies the needed cells')")
assert evaluate("document.querySelectorAll('.udc-question-card')[99].innerText.includes('source checked · not scored')")
browse('Sub-Inspector FCS&CA / Receptionist H&FW', 'General English')
assert evaluate("document.querySelectorAll('.udc-question-card').length === 63")
assert evaluate("document.querySelectorAll('.udc-question-card')[0].innerText.includes('Gentle') && document.querySelectorAll('.udc-question-card')[60].innerText.includes('Write a précis')")
evaluate("document.querySelectorAll('.udc-question-card')[38].querySelectorAll('.udc-option-label')[1].closest('button').click()")
wait_for("document.querySelectorAll('.udc-question-card')[38].innerText.includes('correct spelling is “precipitous”')")
browse('Stenographer Grade II, MPSC', 'General English')
assert evaluate("document.querySelectorAll('.udc-question-card').length === 44")
evaluate("document.querySelectorAll('.udc-question-card')[0].querySelectorAll('.udc-option-label')[2].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[0].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[0].innerText.includes('functions as an adverb')")
browse('Motor Vehicle Inspector', 'General Knowledge')
assert evaluate("document.querySelectorAll('.udc-question-card').length === 100")
evaluate("document.querySelectorAll('.udc-question-card')[0].querySelectorAll('.udc-option-label')[3].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[0].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[0].innerText.includes('Mizoram was officially declared India’s first fully literate state')")
assert evaluate("document.querySelectorAll('.udc-question-card')[67].innerText.includes('Which pollutant is not included')")
assert evaluate("document.querySelectorAll('.udc-question-card')[68].innerText.includes('According to the 2022 All India Tiger Estimation')&&document.querySelectorAll('.udc-question-card')[69].innerText.includes('Biosphere Reserves')")
evaluate("document.querySelectorAll('.udc-question-card')[67].querySelectorAll('.udc-option-label')[3].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[67].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[67].innerText.includes('Carbon dioxide is not on that list')")
evaluate("document.querySelectorAll('.udc-question-card')[71].querySelectorAll('.udc-option-label')[2].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[71].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[71].innerText.includes('1,850 hectares')")
assert evaluate("document.querySelectorAll('.udc-question-card')[86].innerText.includes('The Cheraw dance is believed to have originated')")
assert evaluate("document.querySelectorAll('.udc-question-card')[91].innerText.includes('Which among the following regarding Zawlbuk')&&document.querySelectorAll('.udc-question-card')[92].innerText.includes('Lianpui Village')")
assert evaluate("document.querySelectorAll('.udc-question-card')[93].innerText.includes('Which statement regarding traditional mizo dance is incorrect')")
assert evaluate("document.querySelectorAll('.udc-question-card')[96].innerText.includes('first Mizo to be awarded the Padma Shri')&&document.querySelectorAll('.udc-question-card')[99].innerText.includes('Which pioneer missionary is credited')")
evaluate("document.querySelectorAll('.udc-question-card')[93].querySelectorAll('.udc-option-label')[1].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[93].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[93].innerText.includes('Cheraw is commonly identified as the oldest')")
for card,option,phrase in [(86,1,'Rawkhatlak'),(91,0,'discontinued in 1938'),(96,3,'first Mizo recipient'),(99,2,'R. A. Lorrain')]:
    evaluate(f"document.querySelectorAll('.udc-question-card')[{card}].querySelectorAll('.udc-option-label')[{option}].closest('button').click()")
    wait_for(f"!!document.querySelectorAll('.udc-question-card')[{card}].querySelector('.udc-answer-sources')")
    assert evaluate(f"document.querySelectorAll('.udc-question-card')[{card}].innerText.includes({json.dumps(phrase)})")
evaluate("document.querySelectorAll('.udc-question-card')[65].querySelectorAll('.udc-option-label')[0].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[65].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[65].innerText.includes('An invasive species is introduced outside its native range')")
evaluate("document.querySelectorAll('.udc-question-card')[21].querySelectorAll('.udc-option-label')[2].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[21].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[21].innerText.includes('Gandhi gave the “Do or Die” call')")
browse('Group B technical common exam', 'General Studies')
assert evaluate("document.querySelectorAll('.udc-question-card').length === 100")
assert evaluate("document.querySelectorAll('.udc-question-card')[3].innerText.includes('30% combined customs duty')")
assert evaluate("document.querySelectorAll('.udc-question-card')[13].innerText.includes('Kanchenjunga')")
assert evaluate("document.querySelectorAll('.udc-question-card')[23].innerText.includes('received Presidential assent on:')&&document.querySelectorAll('.udc-question-card')[27].innerText.includes('How many Fundamental Duties')")
evaluate("document.querySelectorAll('.udc-question-card')[23].querySelectorAll('.udc-option-label')[1].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[23].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[23].innerText.includes('came into force on 12 October 2005')")
assert evaluate("document.querySelectorAll('.udc-question-card')[43].innerText.includes('Hlukhla Kut')&&document.querySelectorAll('.udc-question-card')[49].innerText.includes('Dampa Tiger Reserve')&&document.querySelectorAll('.udc-question-card')[56].innerText.includes('new Chief Justice of India')")
evaluate("document.querySelectorAll('.udc-question-card')[43].querySelectorAll('.udc-option-label')[1].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[43].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[43].innerText.includes('late February or early March')")
assert evaluate("document.querySelectorAll('.udc-question-card')[67].innerText.includes('82°30′ E')&&document.querySelectorAll('.udc-question-card')[74].innerText.includes('widely used definition')&&document.querySelectorAll('.udc-question-card')[79].innerText.includes('World Economic Forum')")
evaluate("document.querySelectorAll('.udc-question-card')[67].querySelectorAll('.udc-option-label')[1].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[67].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[67].innerText.includes('Standard Meridian is 82°30′ E')")
evaluate("document.querySelectorAll('.udc-question-card')[3].querySelectorAll('.udc-option-label')[2].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[3].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[3].innerText.includes('10% customs duty plus a 20% Agriculture Infrastructure')")
browse('Stenographer Grade II, DP&AR', 'General Knowledge')
assert evaluate("document.querySelectorAll('.udc-question-card').length === 100")
assert evaluate("document.querySelectorAll('.udc-question-card')[0].innerText.includes('longest ever serving Chief Minister')")
assert evaluate("document.querySelectorAll('.udc-question-card')[43].innerText.includes('Latvia joined on 1 January 2014')&&document.querySelectorAll('.udc-question-card')[43].innerText.includes('Held unscored')")
assert evaluate("document.querySelectorAll('.udc-question-card')[99].innerText.includes('Headquarters of the UN')&&document.querySelectorAll('.udc-question-card')[99].innerText.includes('Held unscored')")
evaluate("document.querySelectorAll('.udc-question-card')[0].querySelectorAll('.udc-option-label')[1].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[0].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[0].innerText.includes('served as chief minister of Sikkim continuously')")
browse('Stenographer Grade III, DP&AR', 'General Knowledge')
assert evaluate("document.querySelectorAll('.udc-question-card').length === 87")
assert evaluate("document.querySelectorAll('.udc-question-card')[0].innerText.includes('first atomic bomb')")
assert evaluate("document.querySelectorAll('.udc-question-card')[86].innerText.includes('Thitin')")
assert evaluate("!document.body.innerText.includes('Question 67')")
evaluate("document.querySelectorAll('.udc-question-card')[83].querySelectorAll('.udc-option-label')[3].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[83].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[83].innerText.includes('Fano dawi was a village sacrifice')")
browse('Stenographer Grade III, Lokayukta', 'General Knowledge')
assert evaluate("document.querySelectorAll('.udc-question-card').length === 100")
assert evaluate("document.querySelectorAll('.udc-question-card')[99].innerText.includes('DP&AR (SSW)')")
assert evaluate("!document.querySelectorAll('.udc-question-card')[99].innerText.includes('Text extraction needs comparison')")
browse('Sub-Inspector of Excise & Narcotics', 'General English')
excise_count = evaluate("document.querySelectorAll('.udc-question-card').length")
assert excise_count == 33, excise_count  # 30 MCQs plus three reviewed written prompts.
assert evaluate("Array.from(document.querySelectorAll('.udc-question-card')).some(card => card.innerText.includes('Write a précis'))")
assert evaluate("Array.from(document.querySelectorAll('.udc-question-card')).some(card => card.innerText.includes('formal letter'))")
assert evaluate("Array.from(document.querySelectorAll('.udc-question-card')).some(card => card.innerText.includes('Little Tramp'))")
evaluate("document.querySelectorAll('.udc-question-card')[23].querySelectorAll('.udc-option-label')[1].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[23].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[23].innerText.includes('comparative rather than a complex clause')")
browse('Sub-Inspector of Excise & Narcotics', 'General Knowledge & Reasoning')
assert evaluate("document.querySelectorAll('.udc-question-card').length === 100")
assert evaluate("document.querySelectorAll('.udc-question-card')[0].innerText.includes('Bharat Parv 2025') && document.querySelectorAll('.udc-question-card')[47].innerText.includes('A. G. McCall')")
assert evaluate("[95,96,97].every(i => document.querySelectorAll('.udc-question-card')[i].querySelector('img')?.getAttribute('src').includes('si-excise-2025-p2-q09'))")
evaluate("document.querySelectorAll('.udc-question-card')[47].querySelectorAll('.udc-option-label')[0].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[47].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[47].innerText.includes('Lushai Chrysalis')")
evaluate("document.querySelectorAll('.udc-question-card')[97].querySelectorAll('.udc-option-label')[2].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[97].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[97].innerText.includes('nested circles')")
assert evaluate("[81].every(i => document.querySelectorAll('.udc-question-card')[i].innerText.includes('source checked · not scored'))")
click_tab('Group B papers')
evaluate("[...document.querySelectorAll('.udc-library-sitting')].find(s=>s.innerText.includes('August 2024')&&s.innerText.includes('Sub-Inspector of Excise & Narcotics')).querySelectorAll('.udc-library-paper').forEach(p=>{if(p.querySelector('strong').textContent.trim()==='General Knowledge')p.querySelector('button')?.click()})")
wait_for("document.querySelectorAll('.udc-question-card').length === 100")
assert evaluate("document.querySelectorAll('.udc-question-card').length === 100")
assert evaluate("document.querySelectorAll('.udc-question-card')[0].innerText.includes('digital electronic device') && document.querySelectorAll('.udc-question-card')[50].innerText.includes('greatest natural number')")
assert evaluate("document.querySelectorAll('.udc-question-card')[51].querySelector('img')?.getAttribute('src').includes('si-excise-2024-p2-q052.png') && document.querySelectorAll('.udc-question-card')[85].querySelector('img')?.getAttribute('src').includes('q086.png') && document.querySelectorAll('.udc-question-card')[90].querySelector('img')?.getAttribute('src').includes('q091.png')")
evaluate("document.querySelectorAll('.udc-question-card')[50].querySelectorAll('.udc-option-label')[3].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[50].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[50].innerText.includes('product of four consecutive integers')")
assert evaluate("[51,90].every(i => document.querySelectorAll('.udc-question-card')[i].innerText.includes('source checked · not scored'))")
click_tab('Group B papers')
evaluate("[...document.querySelectorAll('.udc-library-sitting')].find(s=>s.innerText.includes('August 2024')&&s.innerText.includes('Sub-Inspector of Excise & Narcotics')).querySelectorAll('.udc-library-paper').forEach(p=>{if(p.querySelector('strong').textContent.trim()==='General English')p.querySelector('button')?.click()})")
wait_for("document.querySelectorAll('.udc-question-card').length === 100")
assert evaluate("document.querySelectorAll('.udc-question-card').length === 100")
assert evaluate("document.querySelectorAll('.udc-question-card')[1].innerText.includes('Which article of the Constitution of India') && document.querySelectorAll('.udc-question-card')[90].innerText.includes('primary purpose of power foods')")
assert evaluate("document.querySelectorAll('.udc-question-card')[0].innerText.includes('1951–56') && document.querySelectorAll('.udc-question-card')[6].innerText.includes('source checked · not scored') && document.querySelectorAll('.udc-question-card')[1].innerText.includes('Article 371G')")
evaluate("document.querySelectorAll('.udc-question-card')[0].querySelectorAll('.udc-option-label')[2].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[0].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[0].innerText.includes('ran from 1951 to 1956')")
evaluate("document.querySelectorAll('.udc-question-card')[51].querySelectorAll('.udc-option-label')[0].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[51].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[51].innerText.includes('Might can express a possibility')")
assert evaluate("document.querySelectorAll('.udc-question-card')[69].innerText.includes('source checked · not scored') && document.querySelectorAll('.udc-question-card')[70].innerText.includes('source checked · not scored')")
assert evaluate("document.querySelectorAll('.udc-question-card')[76].innerText.includes('The worst days of any summer') && document.querySelectorAll('.udc-question-card')[81].innerText.includes('Hooker covertly moved 70,000') && document.querySelectorAll('.udc-question-card')[95].innerText.includes('sulphur compounds in onion and garlic')")
assert evaluate("getComputedStyle(document.querySelectorAll('.udc-question-card')[76].querySelector('.udc-question-direction')).whiteSpace === 'pre-line'")
browse('AAO / AAAO / Field Facilitator', 'General Knowledge')
assert evaluate("document.querySelectorAll('.udc-question-card').length === 100")
assert evaluate("document.querySelectorAll('.udc-question-card')[0].innerText.includes('NISAR') && document.querySelectorAll('.udc-question-card')[1].innerText.includes('50% tariff') && document.querySelectorAll('.udc-question-card')[5].innerText.includes('Consider these statements about 2025') && document.querySelectorAll('.udc-question-card')[5].innerText.includes('source is checked; this item is held unscored')")
evaluate("document.querySelectorAll('.udc-question-card')[0].querySelectorAll('.udc-option-label')[0].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[0].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[0].innerText.includes('low-Earth-orbit observatory')")
assert evaluate("document.querySelectorAll('.udc-question-card')[29].innerText.includes('Mizoram Sustainable Investment Policy')")
evaluate("document.querySelectorAll('.udc-question-card')[29].querySelectorAll('.udc-option-label')[1].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[29].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[29].innerText.includes('aims to attract private investment')")
assert evaluate("document.querySelectorAll('.udc-question-card')[43].innerText.includes('chronological order') && document.querySelectorAll('.udc-question-card')[45].innerText.includes('7 days')")
assert evaluate("document.querySelectorAll('.udc-question-card')[55].innerText.includes('√3:1')")
evaluate("document.querySelectorAll('.udc-question-card')[55].querySelectorAll('.udc-option-label')[3].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[55].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[55].innerText.includes('giving AB:BC = √3:1')")
evaluate("document.querySelectorAll('.udc-question-card')[51].querySelectorAll('.udc-option-label')[3].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[51].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[51].innerText.includes('largest such five-digit number is 99,370')")
evaluate("document.querySelectorAll('.udc-question-card')[52].querySelectorAll('.udc-option-label')[0].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[52].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[52].innerText.includes('Adding 1 gives 1 4/5')")
assert evaluate("document.querySelectorAll('.udc-question-card')[82].innerText.includes('Walk') && document.querySelectorAll('.udc-question-card')[97].innerText.includes('Figure (d): two separate small circles wholly inside one larger circle')")
assert evaluate("document.querySelectorAll('.udc-question-card')[98].innerText.includes('Eight people, A, B, C, D, E, F, G and H') && document.querySelectorAll('.udc-question-card')[99].innerText.includes('Eight people, A, B, C, D, E, F, G and H')")
browse('Junior Engineer, LAD, PWD & I&WR', 'General Knowledge')
assert evaluate("document.querySelectorAll('.udc-question-card').length === 100")
assert evaluate("document.querySelectorAll('.udc-question-card')[0].innerText.includes('first skywalk in Mizoram') && document.querySelectorAll('.udc-question-card')[12].innerText.includes('24th')")
assert evaluate("document.querySelectorAll('.udc-question-card')[13].innerText.includes('326 BC') && document.querySelectorAll('.udc-question-card')[13].innerText.includes('not scored')")
assert evaluate("document.querySelectorAll('.udc-question-card')[48].innerText.includes('Environmental sustainability')")
evaluate("document.querySelectorAll('.udc-question-card')[49].querySelectorAll('.udc-option-label')[1].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[49].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[49].innerText.includes('overlapping deprivations in health, education and standard of living')")
assert evaluate("document.querySelectorAll('.udc-question-card')[59].innerText.includes('Networks of relationships among people in a society')")
evaluate("document.querySelectorAll('.udc-question-card')[96].querySelectorAll('.udc-option-label')[3].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[96].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[96].innerText.includes('last chief to maintain resistance')")
evaluate("document.querySelectorAll('.udc-question-card')[98].querySelectorAll('.udc-option-label')[3].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[98].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[98].innerText.includes('Reginald A. Lorrain founded the Lakher Pioneer Mission in 1907')")
evaluate("document.querySelectorAll('.udc-question-card')[7].querySelectorAll('.udc-option-label')[2].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[7].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[7].innerText.includes('projected real GDP growth of 6.7%')")
browse('Assistant Audit & Accounts Officer', 'General Knowledge')
browse('Assistant Audit & Accounts Officer', 'General Knowledge')
assert evaluate("document.querySelectorAll('.udc-question-card').length") == 100
assert evaluate("document.querySelectorAll('.udc-question-card')[2].innerText.includes('The Esya Centre')")
assert evaluate("document.querySelectorAll('.udc-question-card')[87].innerText.includes('Jayalalithaa')")
assert evaluate("document.querySelectorAll('.udc-question-card')[1].innerText.includes('Bharat Diwas')")
assert evaluate("document.querySelectorAll('.udc-question-card')[10].innerText.includes('10 February 2020')")
assert evaluate("document.querySelectorAll('.udc-question-card')[98].innerText.includes('Generally Accepted Accounting Principles')")
assert evaluate("document.querySelectorAll('.udc-question-card')[99].innerText.includes('12,742 km')")
evaluate("document.querySelectorAll('.udc-question-card')[12].querySelector('.udc-option-label').closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[12].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[12].querySelector('.udc-answer-sources').innerText.includes('B / D')")
evaluate("document.querySelectorAll('.udc-question-card')[72].querySelectorAll('.udc-option-label')[1].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[72].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[72].innerText.includes('Text and option order checked')")
assert evaluate("document.querySelectorAll('.udc-question-card')[72].querySelector('.udc-answer-sources a').href.includes('corrigendum')")
assert evaluate("(async()=>{let a=document.querySelectorAll('.udc-question-card')[72].querySelector('.udc-answer-sources a');return (await fetch(a.href)).status})()") == 200
browse('Assistant Audit & Accounts Officer', 'General English')
evaluate("document.querySelectorAll('.udc-question-card')[36].querySelectorAll('.udc-option-label')[1].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[36].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[36].innerText.includes('tenacious of life')")
evaluate("document.querySelectorAll('.udc-question-card')[76].querySelectorAll('.udc-option-label')[3].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[76].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[76].innerText.includes('obstruct or hinder')")
assert evaluate("document.querySelectorAll('.udc-question-card').length") == 100
assert evaluate("document.querySelectorAll('.udc-question-card')[0].querySelector('.udc-question-stem').querySelector('.udc-blank') && document.querySelectorAll('.udc-question-card')[0].innerText.includes(\"this task by lunch\")")
evaluate("document.querySelectorAll('.udc-question-card')[0].querySelectorAll('.udc-option-label')[1].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[0].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[0].innerText.includes('future perfect')")
assert evaluate("Array.from(document.querySelectorAll('.udc-question-card')).some(card => card.innerText.includes('Cats are tenacious') && !card.innerText.includes('held out from scoring'))")
assert evaluate("Array.from(document.querySelectorAll('.udc-question-card')).some(card => card.innerText.includes('Given below are four jumbled sentences'))")
assert evaluate("Array.from(document.querySelectorAll('.udc-question-card')).some(card => card.innerText.includes('antonym of “waver”'))")
assert evaluate("Array.from(document.querySelectorAll('.udc-question-card')).some(card => card.innerText.includes('Come in the way of') && !card.innerText.includes('held out from scoring'))")
assert evaluate("document.querySelectorAll('.udc-question-card')[99].innerText.includes('LATENT')")
browse('Assistant Audit & Accounts Officer', 'Arithmetic')
evaluate("document.querySelectorAll('.udc-question-card')[74].querySelectorAll('.udc-option-label')[3].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[74].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[74].innerText.includes('8:12:15')")
assert evaluate("document.querySelectorAll('.udc-question-card').length") == 100
assert evaluate("document.querySelectorAll('.udc-question-card')[0].innerText.includes('value of √2')")
evaluate("document.querySelectorAll('.udc-question-card')[0].querySelectorAll('.udc-option-label')[0].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[0].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[0].innerText.includes('three decimal places')")
evaluate("document.querySelectorAll('.udc-question-card')[6].querySelectorAll('.udc-option-label')[3].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[6].querySelector('.udc-answer-sources')")
assert evaluate("Array.from(document.querySelectorAll('.udc-question-card')).some(card => card.innerText.includes('number of terms in the sequence') && card.innerText.includes('Legacy inferred candidate gives C'))")
assert evaluate("Array.from(document.querySelectorAll('.udc-question-card')).some(card => card.innerText.includes('speed of a moving car is 36 km/hr'))")
evaluate("(()=>{const c=Array.from(document.querySelectorAll('.udc-question-card')).find(card=>card.innerText.includes('How many bricks'));if(!c)throw Error('Q30 not rendered');c.querySelectorAll('.udc-option-label')[0].closest('button').click()})()")
wait_for("!!Array.from(document.querySelectorAll('.udc-question-card')).find(card=>card.innerText.includes('How many bricks'))?.querySelector('.udc-answer-sources')")
assert evaluate("Array.from(document.querySelectorAll('.udc-question-card')).some(card => card.innerText.includes('How many bricks') && card.innerText.includes('Compensated · not scored') && card.innerText.includes('held out from scoring'))")
assert evaluate("Array.from(document.querySelectorAll('.udc-question-card')).some(card => card.innerText.includes('frequency distribution table') && card.innerText.includes('median class'))")
evaluate("(()=>{const c=Array.from(document.querySelectorAll('.udc-question-card')).find(card=>card.innerText.includes('Evaluate')&&card.innerText.includes('4096'));if(!c)throw Error('Q52 not rendered');c.querySelectorAll('.udc-option-label')[1].closest('button').click()})()")
wait_for("!!Array.from(document.querySelectorAll('.udc-question-card')).find(card=>card.innerText.includes('Evaluate')&&card.innerText.includes('4096'))?.querySelector('.udc-answer-sources')")
assert evaluate("Array.from(document.querySelectorAll('.udc-question-card')).some(card => card.innerText.includes('4096') && card.innerText.includes('∛64=4'))")
evaluate("(()=>{const c=Array.from(document.querySelectorAll('.udc-question-card')).find(card=>card.innerText.includes('probability of drawing a white ball'));if(!c)throw Error('Q63 not rendered');c.querySelectorAll('.udc-option-label')[3].closest('button').click()})()")
wait_for("!!Array.from(document.querySelectorAll('.udc-question-card')).find(card=>card.innerText.includes('probability of drawing a white ball'))?.querySelector('.udc-answer-sources')")
assert evaluate("Array.from(document.querySelectorAll('.udc-question-card')).some(card => card.innerText.includes('probability of drawing a white ball') && card.innerText.includes('g=4'))")
evaluate("(()=>{const c=Array.from(document.querySelectorAll('.udc-question-card')).find(card=>card.innerText.includes('How many like hockey only'));if(!c)throw Error('hockey Q not rendered');c.querySelectorAll('.udc-option-label')[3].closest('button').click()})()")
wait_for("!!Array.from(document.querySelectorAll('.udc-question-card')).find(card=>card.innerText.includes('How many like hockey only'))?.querySelector('.udc-answer-sources')")
assert evaluate("Array.from(document.querySelectorAll('.udc-question-card')).some(card => card.innerText.includes('How many like hockey only') && card.innerText.includes('official MPSC final key marks option D, 25'))")
assert evaluate("Array.from(document.querySelectorAll('.udc-question-card')).some(card => card.innerText.includes('a:b=2:3') && card.innerText.includes('scale 2:3 to 8:12'))")
assert evaluate("document.querySelectorAll('.udc-question-card')[99].innerText.includes('3 m broad')")
evaluate("document.querySelectorAll('.udc-question-card')[99].querySelectorAll('.udc-option-label')[3].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[99].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[99].innerText.includes('15,000 litres')")
evaluate("(()=>{const c=Array.from(document.querySelectorAll('.udc-question-card')).find(card=>card.innerText.includes('A and B can do a job together in 12 days'));if(!c)throw Error('Q93 not rendered');c.querySelectorAll('.udc-option-label')[3].closest('button').click()})()")
wait_for("!!Array.from(document.querySelectorAll('.udc-question-card')).find(card=>card.innerText.includes('A and B can do a job together in 12 days'))?.querySelector('.udc-answer-sources')")
assert evaluate("Array.from(document.querySelectorAll('.udc-question-card')).some(card => card.innerText.includes('A and B can do a job together in 12 days') && card.innerText.includes('36 days'))")
browse('Sub-Inspector of Police (Un-armed Branch)', 'General Knowledge & Reasoning')
assert evaluate("document.querySelectorAll('.udc-question-card').length == 100")
assert evaluate("Array.from(document.querySelectorAll('.udc-question-card')).some(card=>card.innerText.includes('Which diagram shows the relationship')&&card.querySelector('img')?.src.includes('si-police-2026-p2-q089.png'))")
assert evaluate("Array.from(document.querySelectorAll('.udc-question-card')).some(card=>card.innerText.includes('survey of 300 students')&&card.querySelector('img')?.src.includes('si-police-2026-p2-q096.png'))")
evaluate("(()=>{const c=Array.from(document.querySelectorAll('.udc-question-card')).find(card=>card.innerText.includes('arrow matrix'));if(!c||!c.querySelector('img')?.src.includes('si-police-2026-p2-q097.png'))throw Error('Q97 image missing');c.querySelectorAll('.udc-option-label')[1].closest('button').click()})()")
wait_for("Array.from(document.querySelectorAll('.udc-question-card')).find(card=>card.innerText.includes('arrow matrix'))?.innerText.includes('Figure 2 has two upward arrows')")
evaluate("(()=>{const c=Array.from(document.querySelectorAll('.udc-question-card')).find(card=>card.innerText.includes('shading pattern'));if(!c||!c.querySelector('img')?.src.includes('si-police-2026-p2-q098.png'))throw Error('Q98 image missing');c.querySelectorAll('.udc-option-label')[0].closest('button').click()})()")
wait_for("Array.from(document.querySelectorAll('.udc-question-card')).find(card=>card.innerText.includes('shading pattern'))?.innerText.includes('right half')")
browse('Sub-Inspector of Police (Un-armed Branch)', 'General English')
assert evaluate("Array.from(document.querySelectorAll('.udc-question-card')).some(card=>card.innerText.includes('The detrimental effects of social media')&&card.innerText.includes('The impact of Artificial Intelligence'))")
assert evaluate("Array.from(document.querySelectorAll('.udc-question-card')).some(card=>card.innerText.includes('Write a précis')&&card.innerText.includes('Reading is one of the most valuable habits'))")
assert evaluate("Array.from(document.querySelectorAll('.udc-question-card')).some(card=>card.innerText.includes('Which kind of human beings denounce studies?')&&card.innerText.includes('According to the author, why should one read?')&&card.innerText.includes('weigh and consider'))")
evaluate("(()=>{const c=Array.from(document.querySelectorAll('.udc-question-card')).find(card=>card.innerText.includes('She')&&card.innerText.includes('a lot of books'));if(!c)throw Error('books Q not rendered');c.querySelectorAll('.udc-option-label')[1].closest('button').click()})()")
wait_for("Array.from(document.querySelectorAll('.udc-question-card')).find(card=>card.innerText.includes('She')&&card.innerText.includes('a lot of books'))?.innerText.includes('multi-valued')")
evaluate("(()=>{const c=Array.from(document.querySelectorAll('.udc-question-card')).find(card=>card.innerText.includes('They said that they took the bus every day'));if(!c)throw Error('Q48 missing');c.querySelectorAll('.udc-option-label')[3].closest('button').click()})()")
wait_for("Array.from(document.querySelectorAll('.udc-question-card')).find(card=>card.innerText.includes('They said that they took the bus every day'))?.innerText.includes('official final key has no answer')")
browse('Sub-Inspector of Police (Un-armed Branch)', 'General Knowledge & Reasoning')
assert evaluate("Array.from(document.querySelectorAll('.udc-question-card')).some(card=>card.innerText.includes('A sum becomes ₹2,400')&&card.innerText.includes('₹1,935.48'))")
browse('Inspector of Statistics', 'General Knowledge & General Mathematics')
assert evaluate("document.querySelectorAll('.udc-question-card').length == 100")
evaluate("document.querySelectorAll('.udc-question-card')[0].querySelectorAll('.udc-option-label')[0].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[0].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[0].innerText.includes('sites in Haryana')")
evaluate("document.querySelectorAll('.udc-question-card')[1].querySelectorAll('.udc-option-label')[2].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[1].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[1].innerText.includes('National Assembly came first')")
evaluate("document.querySelectorAll('.udc-question-card')[16].querySelectorAll('.udc-option-label')[0].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[16].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[16].innerText.includes('Yuktdhara supports geospatial planning')")
evaluate("document.querySelectorAll('.udc-question-card')[19].querySelectorAll('.udc-option-label')[0].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[19].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[19].innerText.includes('Consumer Price Index measures changes')")
evaluate("document.querySelectorAll('.udc-question-card')[20].querySelectorAll('.udc-option-label')[0].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[20].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[20].innerText.includes('Blue carbon is carbon captured')")
evaluate("document.querySelectorAll('.udc-question-card')[26].querySelectorAll('.udc-option-label')[0].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[26].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[26].innerText.includes('launched the Parker Solar Probe in 2018')")
assert evaluate("document.querySelectorAll('.udc-question-card')[27].innerText.includes('no “I, II, III and IV” answer')")
evaluate("document.querySelectorAll('.udc-question-card')[37].querySelectorAll('.udc-option-label')[1].closest('button').click()")
wait_for("!!document.querySelectorAll('.udc-question-card')[37].querySelector('.udc-answer-sources')")
assert evaluate("document.querySelectorAll('.udc-question-card')[37].innerText.includes('train travels 12.5 m/s')&&document.querySelectorAll('.udc-question-card')[37].innerText.includes('245 m')")
click_tab('Group B papers')
assert evaluate("document.querySelector('.udc-library-progress').innerText.includes('11,308 items need source review')")
assert evaluate("document.querySelector('.udc-library-progress').innerText.includes('36 checked items held unscored')")
assert evaluate("document.querySelector('.udc-library-progress').innerText.includes('154 questions not recovered from source')")
for exam, count, needle in (
    ('Inspector of Statistics · February 2017', 10, 'classical realist'),
    ('Group B technical common exam · November 2024', 10, 'Sir Leon'),
    ('Assistant Sub-Inspector of Police (Ministerial)', 12, 'Natural disasters'),
    ('Motor Vehicle Inspector', 13, 'cinema'),
):
    browse(exam, 'General English')
    assert evaluate(f"document.querySelectorAll('.udc-question-card').length === {count}")
    assert evaluate(f"Array.from(document.querySelectorAll('.udc-question-card')).some(c=>c.innerText.includes({json.dumps(needle)}))")
    assert evaluate("Array.from(document.querySelectorAll('.udc-question-card')).every(c=>!c.querySelector('.udc-option-label'))")
# Fill-in-the-blank written drills: a `_____` run renders as a ruled line, and
# "Reveal model answer" drops each answer into its slot so the stem completes
# like an answer sheet. The 2017 Inspector of Statistics English paper holds the
# two ten-blank grammar drills (verbs and adjectives).
browse('Inspector of Statistics · February 2017', 'General English')
wait_for("Array.from(document.querySelectorAll('.udc-question-card')).some(c=>c.innerText.includes('Put the adjectives in the correct form'))")
for needle, filled, n, revealed in (
    ('Put the adjectives in the correct form', 'the coldest', 10, '(bad) worse than buying'),
    ('Fill in the blanks using the correct form of the verb', 'was playing', 10, 'few days ago. (already be)'),
):
    stem = f"(()=>{{const c=Array.from(document.querySelectorAll('.udc-question-card')).find(card=>card.innerText.includes({json.dumps(needle)}));if(!c)throw Error('drill not rendered');c.scrollIntoView({{block:'center'}});return c.querySelector('.udc-question-stem')}})()"
    wait_for(f"!!({stem})")
    # Pre-reveal: every blank is a ruled line, no literal underscores left.
    assert evaluate(f"({stem}).querySelectorAll('.udc-blank').length === {n}")
    assert evaluate(f"({stem}).innerText.includes('_') === false")
    evaluate(f"[...({stem}).closest('.udc-question-card').querySelectorAll('button')].find(b=>b.textContent.includes('Reveal model answer')).click()")
    # Post-reveal: every blank carries its model answer; the stem reads completed.
    wait_for(f"({stem}).querySelectorAll('.udc-blank-fill').length === {n}")
    assert evaluate(f"({stem}).querySelectorAll('.udc-blank').length === 0")
    assert evaluate(f"({stem}).innerText.includes({json.dumps(filled)})")
    assert evaluate(f"({stem}).innerText.includes({json.dumps(revealed)})")
browse('Junior Engineer, Agriculture & Farmer Welfare', 'General English')
assert evaluate("document.querySelectorAll('.udc-question-card').length === 34")
assert evaluate("document.querySelectorAll('.udc-question-card')[8].querySelector('u')?.textContent === 'little'")
assert evaluate("document.querySelectorAll('.udc-question-card')[28].innerText.includes('source checked · not scored')")
browse('Junior Engineer, LAD, PWD & I&WR', 'General English')
assert evaluate("document.querySelectorAll('.udc-question-card').length === 63")
assert evaluate("document.querySelectorAll('.udc-question-card')[21].innerText.includes('elaborate')")
assert evaluate("document.querySelectorAll('.udc-question-card')[33].querySelector('a')?.href.includes('#page=8')")
assert evaluate("document.querySelectorAll('.udc-question-card')[25].innerText.includes('source checked · not scored')")
browse('Stenographer Grade III, DP&AR · November 2024', 'General English')
assert evaluate("document.querySelectorAll('.udc-question-card').length === 62")
assert evaluate("Array.from(document.querySelectorAll('.udc-question-card')).some(c=>c.innerText.includes('banking and other financial services'))")
browse('Assistant Sub-Inspector of Police (Ministerial)', 'General Knowledge & Reasoning')
assert evaluate("document.querySelectorAll('.udc-question-card').length === 100")
for index in (61,86,87,88):
    evaluate(f"document.querySelectorAll('.udc-question-card')[{index}].scrollIntoView({{block:'center'}})")
    # Lazy images are sometimes aborted mid-session (complete=true, naturalWidth 0)
    # when React re-renders during paper switching; a fresh <Image> for the same
    # URL decodes fine, so relaunch the load on each poll until it settles.
    wait_for(f"(()=>{{const im=document.querySelectorAll('.udc-question-card')[{index}].querySelector('img');if(im&&!im.naturalWidth&&im.complete){{im.loading='eager';im.src=im.currentSrc||im.src;}}return !!im&&im.naturalWidth>0}})()")
evaluate("document.querySelectorAll('.udc-question-card')[79].querySelectorAll('.udc-option-label')[0].closest('button').click()")
wait_for("document.querySelectorAll('.udc-question-card')[79].innerText.includes('377 × 34/493 = 26')")
# The rail's chip counts come from `railCounts`, a single-pass computation that
# must agree with the filtered LIST the page shows (`applyFilters`). Selecting
# a Section chip and comparing its count with the resulting match count is the
# proof on the live combined bank — a chip that promises 317 and delivers 316
# is exactly the drift the two-layer refactor exists to rule out.
click_tab('browse')
evaluate("[...document.querySelectorAll('button')].find(b=>b.textContent.includes('Filters')&&b.textContent.includes('question'))?.click()")
wait_for("[...document.querySelectorAll('div')].some(d=>d.children[0]?.tagName==='SPAN'&&d.children[0].textContent.trim()==='Section'&&!!d.children[1]?.querySelector('button'))")
# Clear any browsed-paper selection so the rail counts span the WHOLE combined
# bank (7,048 questions), where every section chip is live and meaningful.
evaluate("[...document.querySelectorAll('button')].find(b=>b.textContent.includes('Clear paper selection'))?.click()")
time.sleep(.3)
section_chips = evaluate("(()=>{const grp=[...document.querySelectorAll('div')].find(d=>d.children[0]?.tagName==='SPAN'&&d.children[0].textContent.trim()==='Section'&&d.children[1]?.querySelector('button'));return [...grp.children[1].querySelectorAll('button')].map(b=>({label:b.childNodes[0]?.textContent.trim(),count:parseInt([...b.querySelectorAll('span')].find(s=>s.style.fontVariantNumeric==='tabular-nums')?.textContent||'0',10)}))})()")
assert [c['label'] for c in section_chips] == ['General Knowledge', 'General English', 'Computer Knowledge', 'Arithmetic & General Mathematics', 'Intelligence & Reasoning'], section_chips
assert all(c['count'] > 0 for c in section_chips), section_chips
section_click = "(()=>{const grp=[...document.querySelectorAll('div')].find(d=>d.children[0]?.tagName==='SPAN'&&d.children[0].textContent.trim()==='Section'&&d.children[1]?.querySelector('button'));return [...grp.children[1].querySelectorAll('button')].find(b=>(b.childNodes[0]?.textContent||'').trim()==="
for chip in section_chips:
    label, n = chip['label'], chip['count']
    evaluate(section_click + json.dumps(label) + ")?.click()})()")
    wait_for(f"(()=>{{const d=[...document.querySelectorAll('div')].find(d=>{{const t=d.innerText||'';return /question[s]? match/.test(t)&&/can be marked/.test(t)}});return d?.querySelector('strong')?.textContent === {json.dumps(str(n))}}})()")
    evaluate(section_click + json.dumps(label) + ")?.click()})()")
    time.sleep(.2)
evaluate("[...document.querySelectorAll('button')].find(b=>b.textContent.includes('Filters')&&b.textContent.includes('question'))?.click()")
command('Emulation.setDeviceMetricsOverride', {'width':390,'height':900,'deviceScaleFactor':1,'mobile':True})
assert evaluate("document.body.scrollWidth <= innerWidth")
command('Emulation.setDeviceMetricsOverride', {'width':1280,'height':900,'deviceScaleFactor':1,'mobile':False})
click_tab('exam')
assert evaluate("[...document.querySelectorAll('button')].some(b=>b.textContent.includes('Assistant Audit & Accounts Officer / Assistant Accounts Officer · General English'))")
assert evaluate("![...document.querySelectorAll('button')].some(b=>b.textContent.includes('Assistant Audit & Accounts Officer / Assistant Accounts Officer · Arithmetic'))")
assert evaluate("[...document.querySelectorAll('button')].some(b=>b.textContent.includes('Stenographer Grade III'))")
assert not exceptions, exceptions
print('Browser passed: all 257 paper sources; completed review and held/missing totals; written-only recovery; JE/stenographer/ASI full numbering, emphasis, figures and worked answers; JAO recovery; official comparison and corrigendum; held scoring gates; rail chip counts agree with filtered lists; Exam eligibility; source links; mobile and desktop layout; no runtime exceptions.')
s.close()
