// Newly written practice questions. Sources are the NCERT PDFs named by book code + chapter.
// Each anchor is checked against the original chapter text by build.mjs.
export const questions = [
  // Class 8 · current Social Science
  ['hees102','Which ruler is associated with a policy of sulh-i kul?',['Akbar','Aurangzeb','Alauddin Khalji','Krishnadevaraya'],0,'Akbar used sulh-i kul as an idea of peace with all.','sulh-i-'],
  ['hees102','Which kingdom is associated with Hampi as its capital?',['Ahom','Vijayanagara','Delhi Sultanate','Mughal'],1,'Hampi was the capital of the Vijayanagara Empire.','Hampi'],
  ['hees103','What geographical feature helped the Marathas use mobile warfare and forts?',['Deccan hills and mountains','Thar dunes','Ganga delta','Brahmaputra floodplains'],0,'The western Deccan terrain and hill forts supported Maratha tactics.','forts'],
  ['hees103','Which Maratha leader is especially associated with naval power on the Konkan coast?',['Kanhoji Angre','Nana Phadnavis','Mahadji Shinde','Bajirao I'],0,'Kanhoji Angre built and commanded Maratha naval power.','Kanhoji Angre'],
  ['hees104','Which battle in 1757 strengthened the East India Company in Bengal?',['Buxar','Plassey','Panipat','Talikota'],1,'The Company victory at Plassey was a turning point in Bengal.','Plassey'],
  ['hees104','Which British policy let the Company annex a state when its ruler died without an accepted male heir?',['Subsidiary Alliance','Doctrine of Lapse','Permanent Settlement','Ryotwari'],1,'The Doctrine of Lapse was used to annex such states.','Doctrine of Lapse'],
  ['hees202','Which protest in Amritsar ended in a massacre in 1919?',['Jallianwala Bagh gathering','Dandi March','Quit India meeting','Kakori action'],0,'British troops fired on the gathering at Jallianwala Bagh.','Jallianwala Bagh'],
  ['hees202','Which movement began after the August 1942 call to end British rule?',['Swadeshi','Quit India','Home Rule','Non-Cooperation'],1,'The Quit India movement followed the 1942 resolution and call.','Quit India'],
  ['hees203','What is a stupa primarily associated with?',['Buddhist relics and worship','Mughal court audiences','Colonial rail transport','Maratha naval defence'],0,'Stupas are Buddhist commemorative structures often connected with relics.','stupa'],
  ['hees203','What is the main purpose of a stepwell?',['Store and provide access to water','House a royal throne','Defend a sea port','Mint coins'],0,'Its stepped design lets people reach water as levels change.','stepwell'],
  ['hees208','Which poet-saint used the names Ram and Rahim to challenge rigid religious divisions?',['Kabir','Kalidasa','Amir Khusrau','Tulsidas'],0,'Kabir’s verses often join devotional language across traditions.','Kabir'],
  ['hees208','Which tradition emphasised personal devotion to a deity as a route to moksha?',['Bhakti','Ryotwari','Mansabdari','Mercantilism'],0,'Bhakti centres on devotion and became influential across regions.','bhakti'],
  // Class 9 · current Social Science
  ['iest104','Which period is especially associated with small stone tools called microliths?',['Palaeolithic','Mesolithic','Bronze Age','Iron Age'],1,'Microliths are a characteristic tool of the Mesolithic period.','microlith'],
  ['iest104','Which river is linked to the ancient Egyptian civilisation?',['Nile','Tigris','Yellow River','Indus'],0,'Ancient Egyptian civilisation developed along the Nile.','Nile'],
  ['iest105','Which early Indian assemblies could limit a raja’s authority?',['Sabha and samiti','Jagir and zamindari','Diwan and faujdar','Factory and guild'],0,'Sabha and samiti were assemblies mentioned in early Indian political life.','sabhā'],
  ['iest105','Which empire is associated with Ashoka’s inscriptions?',['Maurya','Gupta','Kushana','Chola'],0,'Ashoka ruled the Mauryan Empire; his edicts are key historical sources.','Aśhoka'],
  // Class 8 · older standalone History
  ['hess201','How did James Mill divide Indian history in his account?',['Ancient, medieval, modern','Hindu, Muslim, British','Rural, urban, industrial','North, south, east'],1,'Mill used Hindu, Muslim and British periods, a division criticised in the chapter.','James Mill'],
  ['hess201','Why did colonial administrators conduct surveys?',['To collect information for governing','To end record keeping','To avoid maps','To replace every census'],0,'Surveys gathered information about land, people and resources for administration.','surveys'],
  ['hess202','What did the Company acquire through the Diwani of Bengal?',['Right to collect land revenue','Right to crown Mughal emperors','Control of all European ports','Rule over Mysore'],0,'The Diwani gave the Company revenue rights in Bengal, Bihar and Orissa.','Diwani'],
  ['hess202','Who was called the Tiger of Mysore?',['Tipu Sultan','Haidar Ali','Mir Jafar','Ranjit Singh'],0,'Tipu Sultan, ruler of Mysore, was known by that title.','Tiger of Mysore'],
  ['hess203','Under the Permanent Settlement, who were recognised as revenue-paying landholders?',['Zamindars','Sepoys','Artisans','Indigo planters'],0,'Zamindars were made responsible for paying fixed revenue to the Company.','Permanent Settlement'],
  ['hess203','What was grown for the blue dye that European textile makers wanted?',['Indigo','Cotton','Jute','Opium'],0,'Indigo plants yielded the blue dye in high demand.','indigo'],
  ['hess204','What is jhum cultivation?',['Shifting cultivation','Permanent wet-rice farming','Urban horticulture','Mining'],0,'Jhum involves clearing and cultivating a plot before moving to another.','jhum'],
  ['hess204','Which leader’s movement imagined a renewed tribal golden age?',['Birsa Munda','Mangal Pandey','Nana Saheb','Dadabhai Naoroji'],0,'Birsa Munda led a movement that invoked a golden age for his people.','Birsa'],
  ['hess205','Which queen of Jhansi became a leader of the 1857 rebellion?',['Rani Lakshmibai','Begum Rokeya','Ahilyabai Holkar','Pandita Ramabai'],0,'Rani Lakshmibai of Jhansi fought the British during the uprising.','Lakshmibai'],
  ['hess205','Why did sepoys object to the new rifle cartridges in 1857?',['They believed the grease violated religious beliefs','They were made of iron','They had no gunpowder','They were too expensive'],0,'Rumours about animal fat in the cartridge grease offended Hindu and Muslim sepoys.','cartridges'],
  ['hess206','Which official argued strongly for English education in India?',['Thomas Macaulay','William Jones','Warren Hastings','Rabindranath Tagore'],0,'Macaulay advocated English education over the Orientalist approach.','Macaulay'],
  ['hess206','Who founded an experimental school at Santiniketan?',['Rabindranath Tagore','Mahatma Gandhi','William Jones','James Mill'],0,'Tagore founded his school at Santiniketan with a different approach to learning.','Santiniketan'],
  ['hess207','Who challenged caste inequality in the book Gulamgiri?',['Jyotirao Phule','Rammohun Roy','Ishwarchandra Vidyasagar','Thomas Macaulay'],0,'Phule used Gulamgiri to criticise caste oppression.','Gulamgiri'],
  ['hess207','Who argued publicly for widow remarriage in nineteenth-century Bengal?',['Ishwarchandra Vidyasagar','Lord Curzon','Bal Gangadhar Tilak','Mir Jafar'],0,'Vidyasagar campaigned for widow remarriage.','Vidyasagar'],
  ['hess208','Which organisation formed in 1885 sought to speak for Indians across regions?',['Indian National Congress','East India Company','Muslim League','Ghadar Party'],0,'The Indian National Congress was founded in 1885 and claimed a national voice.','Indian National Congress'],
  ['hess208','Which law of 1919 allowed detention without trial and drew nationwide protest?',['Rowlatt Act','Vernacular Press Act','Pitt’s India Act','Indian Councils Act 1909'],0,'The Rowlatt Act gave the colonial state sweeping powers of detention.','Rowlatt'],
  // Class 10
  ['jess301','What was the Zollverein?',['A customs union of German states','A French parliament','An Italian revolutionary society','A Balkan treaty'],0,'The Zollverein removed tariff barriers among participating German states.','Zollverein'],
  ['jess301','Who personified the German nation in nineteenth-century allegories?',['Germania','Marianne','Britannia','Liberty'],0,'Germania was an allegorical female figure for the German nation.','Germania'],
  ['jess302','What did Gandhi break at Dandi in 1930?',['Salt law','Forest Act','Rowlatt Act','Press Act'],0,'The Dandi March culminated in breaking the colonial salt law.','Dandi'],
  ['jess302','Why did the Simon Commission face protests in India?',['It had no Indian members','It proposed immediate independence','It banned the Congress','It abolished the salt tax'],0,'Indian leaders objected to the all-British commission.','Simon Commission'],
  ['jess303','What was rinderpest?',['A cattle disease','A European tariff','A shipbuilding method','A grain crop'],0,'Rinderpest was a devastating cattle plague in Africa.','rinderpest'],
  ['jess303','What did abolishing Britain’s Corn Laws allow?',['Cheaper food imports','A ban on grain imports','An end to all migration','The gold standard'],0,'Repeal opened Britain to imported food grain.','Corn Laws'],
  ['jess304','What does proto-industrialisation describe?',['Production for markets before factory industrialisation','The first steam railway','Only urban factory work','Mechanised farming'],0,'The term describes market-oriented production that preceded factories.','proto-industrialisation'],
  ['jess304','Why did some women workers attack the Spinning Jenny?',['They feared losing work','It raised wages too quickly','It banned cotton','It required electricity'],0,'The machine threatened the livelihood of hand spinners.','Spinning Jenny'],
  ['jess305','Who developed a movable-type printing press in Europe?',['Johannes Gutenberg','Martin Luther','Marco Polo','Erasmus'],0,'Gutenberg developed a press using movable metal type.','Gutenberg'],
  ['jess305','Which colonial law gave officials powers over Indian-language newspapers?',['Vernacular Press Act','Rowlatt Act','Salt Act','Regulating Act'],0,'The Vernacular Press Act targeted the Indian-language press.','Vernacular Press Act'],
];
questions.push(
  // Class 11. Chapter file kehs102 contains two separate themes.
  ['kehs101','What script was used to write many ancient Mesopotamian texts?',['Cuneiform','Brahmi','Hieroglyphic','Devanagari'],0,'Mesopotamian scribes pressed wedge-shaped cuneiform signs into clay tablets.','cuneiform'],
  ['kehs101','Which Mesopotamian city is noted for its early urban growth?',['Uruk','Athens','Rome','Pataliputra'],0,'Uruk became one of Mesopotamia’s early large cities.','Uruk'],
  ['kehs102','Which sea linked the Roman Empire’s European, African and Asian provinces?',['Mediterranean','Baltic','Red Sea','Black Sea'],0,'The Mediterranean lay at the centre of Rome’s three-continent empire.','Mediterranean'],
  ['kehs102','Which ruler founded the Roman Principate after civil wars?',['Augustus','Trajan','Diocletian','Constantine'],0,'Augustus established the Principate in 27 BCE.','Augustus'],
  ['kehs102','Who united the Mongol tribes under his leadership?',['Genghis Khan','Qubilai Khan','Timur','Batu'],0,'Genghis Khan united the tribes and founded the Mongol Empire.','Genghis Khan'],
  ['kehs102','What was the yasa associated with in Mongol history?',['Rules attributed to Genghis Khan','Roman tax registers','European feudal dues','Japanese land reforms'],0,'The yasa refers to rules and traditions associated with Genghis Khan.','yasa'],
  ['kehs104','In medieval French society, what did serfs owe a lord?',['Labour and dues','Naval service only','A factory wage','A vote in parliament'],0,'Serfs were tied to land and owed labour and dues to the lord.','serfs'],
  ['kehs104','Which group was expected to pray in the model of the three orders?',['Clergy','Knights','Peasants','Merchants'],0,'The clergy formed the order that prayed.','clergy'],
  ['kehs105','What did Renaissance humanism encourage scholars to study?',['Human life and classical texts','Only feudal land tenure','Only factory production','Only tribal warfare'],0,'Humanists renewed study of classical learning and human experience.','humanism'],
  ['kehs105','Which Italian city is strongly associated with Renaissance art and humanism?',['Florence','London','Moscow','Lisbon'],0,'Florence was a major centre of Renaissance art and learning.','Florence'],
  ['kehs106','What did the American “frontier” refer to?',['The moving edge of settler expansion','A Roman border wall','A fixed colonial tax','A railway timetable'],0,'The term was used for the expanding zone of European-American settlement.','frontier'],
  ['kehs106','Which people lived in Australia before British colonisation?',['Aboriginal peoples','Mongols','Aztecs','Franks'],0,'Aboriginal peoples had lived in Australia long before British settlement.','Aboriginal'],
  ['kehs107','Which Japanese restoration began major state-led modernisation in 1868?',['Meiji Restoration','Qing Restoration','Tokugawa Restoration','Taisho Restoration'],0,'The Meiji Restoration began the reorganisation of Japan’s state and economy.','Meiji'],
  ['kehs107','Which Chinese dynasty faced intensified Western pressure in the nineteenth century?',['Qing','Tang','Han','Sui'],0,'The Qing state faced Western military and commercial demands.','Qing'],
  // Class 12 · Themes in Indian History I
  ['lehs101','Which Harappan structure at Mohenjodaro is associated with ritual bathing?',['Great Bath','Ashokan pillar','Brihadisvara Temple','Diwan-i Am'],0,'The Great Bath is a prominent structure in the citadel at Mohenjodaro.','Great Bath'],
  ['lehs101','Which Harappan site is noted for a sophisticated water-management system?',['Dholavira','Sanchi','Taxila','Hampi'],0,'Dholavira had large reservoirs and a planned water system.','Dholavira'],
  ['lehs102','What were the mahajanapadas?',['Large early states','Mughal tax districts','Maratha forts','British presidencies'],0,'Mahajanapadas were early large territorial states.','mahajanapadas'],
  ['lehs102','Which ruler issued edicts on rocks and pillars across his empire?',['Ashoka','Samudragupta','Harsha','Chandragupta II'],0,'Ashoka’s inscriptions are a major source for Mauryan history.','Asoka'],
  ['lehs103','What does patriliny mean?',['Tracing descent through the father','Tracing descent through the mother','Marriage outside the group','Division of labour'],0,'Patriliny passes descent and inheritance through the male line.','patriliny'],
  ['lehs103','Which text is a central source for the chapter’s discussion of kinship and social norms?',['Mahabharata','Ain-i Akbari','Kitab-ul-Hind','Arthashastra only'],0,'The Mahabharata is used to examine kinship, caste and class.','Mahabharata'],
  ['lehs104','Which teacher is closely associated with the Jain tradition?',['Mahavira','Kabir','Shankaracharya','Guru Nanak'],0,'Mahavira was the twenty-fourth tirthankara of the Jain tradition.','Mahavira'],
  ['lehs104','Which site is famous for Buddhist stupas and sculptured gateways?',['Sanchi','Hampi','Dholavira','Fatehpur Sikri'],0,'Sanchi preserves important Buddhist stupas and gateways.','Sanchi'],
  // Class 12 · Themes in Indian History II
  ['lehs201','Who wrote the Kitab-ul-Hind?',['Al-Biruni','Ibn Battuta','Bernier','Abul Fazl'],0,'Al-Biruni wrote the Kitab-ul-Hind after studying Indian knowledge and society.','Kitab-ul-Hind'],
  ['lehs201','Which traveller from Morocco wrote the Rihla?',['Ibn Battuta','Al-Biruni','Marco Polo','Bernier'],0,'Ibn Battuta’s travel account is known as the Rihla.','Rihla'],
  ['lehs202','Which Sufi order is associated with Muinuddin Chishti?',['Chishti','Qadiri','Naqshbandi','Suhrawardi'],0,'Muinuddin Chishti is an important figure of the Chishti order.','Muinuddin Chishti'],
  ['lehs202','Which devotional poet questioned religious and caste divisions through his verses?',['Kabir','Kalidasa','Bana','Abul Fazl'],0,'Kabir’s verses challenged rigid divisions and emphasised devotion.','Kabir'],
  ['lehs203','What is Hampi associated with?',['The ruins of Vijayanagara','The Mauryan capital','An Indus city','The Mughal capital'],0,'Hampi contains the remains of Vijayanagara’s imperial capital.','Hampi'],
  ['lehs203','Which river flowed near Vijayanagara and supported its water system?',['Tungabhadra','Nile','Ganga','Narmada'],0,'Vijayanagara’s water system drew on the Tungabhadra River.','Tungabhadra'],
  ['lehs204','Which text compiled by Abul Fazl describes Akbar’s administration?',['Ain-i Akbari','Kitab-ul-Hind','Rihla','Gulamgiri'],0,'The Ain-i Akbari is a major source on Mughal administration and agrarian society.','Ain-i Akbari'],
  ['lehs204','Who were zamindars in Mughal agrarian society?',['Local landed intermediaries with claims on revenue','European factory owners','Only palace scribes','Temple priests alone'],0,'Zamindars held local power and claimed a share of agrarian revenue.','zamindars'],
  // Class 12 · Themes in Indian History III
  ['lehs301','Which settlement fixed Bengal’s land revenue demand in 1793?',['Permanent Settlement','Ryotwari Settlement','Mahalwari Settlement','Subsidiary Alliance'],0,'The Permanent Settlement fixed the Company’s land revenue demand on zamindars.','Permanent Settlement'],
  ['lehs301','Which community rebelled in 1855–56 in the Damin-i-Koh region?',['Santhals','Marathas','Sikhs','Ahoms'],0,'The Santhal rebellion grew from conflict over land, debt and colonial rule.','Santhals'],
  ['lehs302','Which Mughal emperor became a symbolic leader of the 1857 rebels?',['Bahadur Shah Zafar','Akbar','Shah Jahan','Aurangzeb'],0,'Rebels sought Bahadur Shah Zafar’s authority to legitimise their cause.','Bahadur Shah'],
  ['lehs302','Which city was a major centre of the 1857 uprising in Awadh?',['Lucknow','Madras','Bombay','Calcutta'],0,'Lucknow was a major centre of rebellion and siege in Awadh.','Lucknow'],
  ['lehs303','Which campaign made the colonial salt tax a symbol of resistance?',['Dandi March','Khilafat Movement','Bardoli Satyagraha','Swadeshi Movement'],0,'Gandhi’s 1930 march to Dandi challenged the salt law.','salt'],
  ['lehs303','Where did Gandhi lead an early satyagraha over indigo cultivation?',['Champaran','Kheda','Dandi','Chauri Chaura'],0,'Gandhi worked with indigo peasants in Champaran in 1917.','Champaran'],
  ['lehs304','Who moved the Objectives Resolution in the Constituent Assembly?',['Jawaharlal Nehru','B. R. Ambedkar','Sardar Patel','Rajendra Prasad'],0,'Nehru moved the Objectives Resolution, which framed the Assembly’s ideals.','Objectives Resolution'],
  ['lehs304','Which language did Gandhi advocate as a bridge between Hindi and Urdu speakers?',['Hindustani','Sanskrit','Persian','English'],0,'Gandhi advocated Hindustani as a language accessible across communities.','Hindustani'],
);
